### ISSUE TITLE
Output label width narrower than layout configuration setting

### ISSUE THREAD

**Issue by mattzman** [ExLibrisGroup/spineomatic-cloudapp#10]
I am trying to print to sheets with labels that are one inch wide. However, the labels generated by the SpineOMatic app are too narrow, by about one-sixteenth of an inch. This is enough to throw off most of the labels in each row.

A sample output file is attached. As far as I can tell, my computer and browser (MacOS/Chrome) are set to print/save the output at 100% scale. 

Here's a link to [the specific labels I'm working with](http://www.shopbrodart.com/Library-Supplies/Circulation-Supplies/Circulation-Labels/Laser-and-Ink-Jet-Labels/_/Brodart-Premium-Quality-Archival-Safe-Labels2/). 

[spine_label_example.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6230644/spine_label_example.pdf)

**Comment by mck1777** [comment]
Hi
Not sure if this helps, but I used 1.03  for my label width instead of 1 to work around that.

mck

**Comment by MaggieMcGee** [comment]
We have a similar issue, but with where the labels start on the sheet compared to where the app prints them. Changing margins in Alma did not work or have any impact.
[20210329091126901_0001.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6239531/20210329091126901_0001.pdf)

**Comment by jweisman** [comment]
Thanks for your comments. I also played with the layout a bit to get it to work out on my printer. I think it may require some trial and error. There was also a bug which mixed up the horizontal and vertical gap which was [fixed](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v0.3.1).

Here's a scan of our labels working and a sketch of the various layout options (in case this helps):

![layout](https://user-images.githubusercontent.com/80420/113508968-c08d9980-955b-11eb-8fb5-897e2ff0e592.png)

[scanned-labels.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6254549/scanned-labels.pdf)

**Comment by jweisman** [comment]
Added the layout diagram to the [documentation](https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#layouts)- hoping this can help others.
