### ISSUE TITLE
"c." printing when no copy Id is in item

### ISSUE THREAD

**Issue by jdavis025** [ExLibrisGroup/spineomatic-cloudapp#101]
Thanks so much for such a helpful app, we're working on implementing it here at Linda Hall Library and we've run into one small snag. For our serials, we shelve by title. In the SpineOMatic client, we use location, call number, issue description, and copy and if there is nothing in the copy id field, it doesn't print the "c."
In the app, we've got it configured to do the same, but it is still printing the "c." when there is nothing there.
![image](https://user-images.githubusercontent.com/26824483/218790481-eeddf2af-4058-4fa0-ab86-4426c07b6f19.png)
Any assistance would be appreciated.
Jane

**Comment by mgobat** [comment]
Fixed for next release.
