### ISSUE TITLE
Template or help with CD/DVD hub labels

### ISSUE THREAD

**Issue by kronneCSU** [ExLibrisGroup/spineomatic-cloudapp#102]
Hello,

I need help with how to format a round hub label. The labels are for use with a Zebra printer, but unfortunately I don't have any spec info on what we are using. The label itself is a donut with an outer diameter of 1.25 and an inner diameter of .75 on a backer of about
1.5 inches square.

[Hub Label Pics.docx](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/10759078/Hub.Label.Pics.docx)

**Comment by mgobat** [comment]
@kronneCSU, wow...this looks tricky. Is it a roll of labels or a sheet of labels? Looks like a roll from your pic. If a roll, single label wide? Maybe these? https://www.thelibrarystore.com/product/16-11362/h

**Comment by kronneCSU** [comment]
They are on a roll. I have like four rolls of our current size. I don't know where we got the rolls we have now, and none of them are in their original packaging. The vendor I work with now sent me specs for a slightly larger size, so once we run out of these, I will probably be ordering from them and will need to tweak the template at that point. Here is the spec sheet. It looks like the inside diameter is the same but the outside diameter is .25 inches larger.

[Computype Hub Label spec sheet.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/10760640/Computype.Hub.Label.spec.sheet.pdf)

**Comment by mgobat** [comment]
@kronneCSU, do you have an example image of what the label should look like when printed?

**Comment by kronneCSU** [comment]
![PXL_20230216_205316698](https://user-images.githubusercontent.com/118297292/219484525-d1998147-a7ff-4884-a56e-9d67adefed86.jpg)

I'm currently in process of deciding if we still need the barcode number or just the library name.

**Comment by mgobat** [comment]
@kronneCSU, using the Computype specs you attached earlier, here are the settings I'd start with for the layout:

Measurement units: inches
Top margin: .1
Left margin: .125
Page width: 2.25
Orientation: Portrait
Label width: 2
Label height: 1.7
Horizontal gap: 0
Vertical gap: .1125
Labels per page: 1
Left padding: .25

Perhaps you can map these to your current label stock measurement to get a starting point for them.

For wrapping the library name around the center hub in the template, I think the best approach would be to create an image of the library name and use that on the label. Maybe a tool like https://www.fotor.com/features/curved-text/ could be used to create the image. I've attached a quick attempt at it. You'd have to play with the sizing, curvature, and opacity to get it right.

![csu](https://user-images.githubusercontent.com/45852490/219497325-b365b217-99a7-426d-8bb2-7ea2f919b465.png)

If you aren't including any information from the Alma holdings/items on the label, might your workstation label printer software be a better option for printing just the library name on the label?

**Comment by kronneCSU** [comment]
What do you mean by workstation label printing software? We already use spine o matic on the desktop.

**Comment by mgobat** [comment]
@kronneCSU, I assumed your label printer came with its own label printing software....my mistake. Sorry.

**Comment by kronneCSU** [comment]
No worries! That would make everything much simpler! Thank you for your help with this.
