### ISSUE TITLE
Make 'Select items' compatible with 'Scan In Items' and 'Return Items' screens

### ISSUE THREAD

**Issue by jonahhighmanUWA** [ExLibrisGroup/spineomatic-cloudapp#103]
The cloud app currently supports a 'Select items' option to choose items to print that are visible in a search results screen.

For our acquisitions and maintenance workflows, it would be a desirable enhancement to be able to print labels using the 'Select items' view directly from the 'Scan In Items' and 'Return Items' screens.

For acquisitions, we currently:

1. Receive the item
2. End process the item
3. Perform cataloguing / copy cataloguing as necessary
3a. This often involves a librarian reviewing the classification 
4. Scanning the item into SpineOMatic desktop to print a label
5. Scanning in the item through 'Scan In Items' to complete the work order.

To embed the cloud app into our acquisitions workflow, it would make a lot of sense to be able to scan in the item/s, click the cloud app, and have the scanned in item/s currently listed on the 'Scan In Items' page available under 'Select items'.

For streamlining high-volume physical acquisitions workflows, this would help reduce duplication and multiple scans of barcodes in different screens, and would aid individual or bulk printing for items in-hand that the operator has already scanned in.

Hopefully the 'Return Items' screen would be similar to implement - for maintenance, our circulation desks each have a spine label printer for easy reprinting of labels as needed, and they primarily use 'Return Items'. If an item is returned, and the CSO notices it needs a new label, they could avoid having to double handle the item by opening it up to scan again, and could print directly from the cloud app using 'Select items'.

**Comment by mgobat** [comment]
@jonahhighmanUWA, this is coming to "Scan In Items" in the June 2024 Alma release. It has not been added for "Return Items".
