### ISSUE TITLE
Keep spacing between fields consistent across labels

### ISSUE THREAD

**Issue by mgobat** [ExLibrisGroup/spineomatic-cloudapp#104]
We'd like the ability to always print the barcode at the bottom of a label, regardless of how many other fields are included to be printed on the label before the barcode.

<img width="263" alt="forceposition" src="https://user-images.githubusercontent.com/45852490/224996875-130f0237-3c8a-4da8-97bb-d2cba97e4dfd.png">

**Comment by mgobat** [comment]
This could be implemented with an option to "Keep label spacing when field empty". With this option checked, when an empty field is encountered for the template, a blank line is inserted instead of nothing. This should keep all fields in the same position across labels.

**Comment by DiederikL** [comment]
Hi, browsing through the open issues concerning SpineOMatic I saw this question. Obviously an additional 'option' would be great but I was facing the same problem and solved it by using a simple one-column/two-rows table. In the upper cell/row I put the call number and I have this cell a fixed height, in de lower cell I put the raw barcode and again a fixed height. You can choose to express the height of each cell either in % (with the sum totaling 100%) or in mm (with the sum totaling the label height set in the layout).
