### ISSUE TITLE
SpineOMatic not working on list of items via Alma Metadata Editor

### ISSUE THREAD

**Issue by DiederikL** [ExLibrisGroup/spineomatic-cloudapp#105]
Hi, 

I noticed a minor inconsistency in the way SpineOMatic selects item barcods from Alma screens. 

If you open a list of items from an Alma search result list of bibliographic records (either by clicking on 'items' below one of the results or first consulting the list of holdings and then calling a list of items for one of these holdings) SpineOMatic correctly 'grabs' the barcodes shown on the list of items and lists them under 'Select items'.

However, if you open a bibliographic record in the Alma Metadata Editor and then call for a list of the inventory (View related data>View inventory) and then call for a list of items linked to a holding (... > View items), Alma shows a 'List of items' identical to the lists you get from a search result list but SpineOMatic does not pick up the barcodes shown on the list. 

I've made a short clip in which this problem is shown: https://kuleuven-my.sharepoint.com/:v:/g/personal/diederik_lanoye_kuleuven_be/Eeay2C1siIFEujebNq1OKjQBoTfjh7-IKTRX_tiua_d5fA?e=q5LBQ1

It is not a major problem but it would be nice to have SpineOMatic ready whenever item data is shown on the Alma screen.

Best regards, 

Diederik Lanoye

LIBIS
KU Leuven Libraries (LIBISnet-consortium, Belgium)

**Comment by mgobat** [comment]
@DiederikL, this is coming in the Alma June release.
