### ISSUE TITLE
Received date format

### ISSUE THREAD

**Issue by jonahhighmanUWA** [ExLibrisGroup/spineomatic-cloudapp#107]
Hi, I have a question (potentially an Alma bug?) and an enhancement request:

I want to use the {{field:item_data.arrival_date}} field ('Receiving date' in the Alma item edit screen) in a pocket label for print journals:
![image](https://user-images.githubusercontent.com/113404105/231631167-5e859b33-499d-4631-ad61-a0f53cf38d6c.png)

The date displays in our Alma item edit screen as `dd/mm/yyyy` (based on our 'system_date_format' setting in Alma):
![image](https://user-images.githubusercontent.com/113404105/231631650-2cc7a2e6-4cc8-49d0-8809-141ef9c4d6e7.png)

The date displays in SpineOMatic cloud app as `yyyy-mm-ddZ`.
![image](https://user-images.githubusercontent.com/113404105/231632054-89e29d7b-c664-48be-bd27-d3e192942fd2.png)
The raw XML for items (checked using SpineOMatic classic app) gives that data with the 'Z' in it, which would be why it comes through on the label. I understand yyyy-mm-dd is ISO standard for coded dates, however I don't know why the 'Z' is there? A 'Z' in the ISO standard indicates GMT for times, however isn't used for dates alone? Do we know if this is Alma's intended behaviour?

Then, is it possible to have a way in SpineOMatic cloud app to customise the date format? Ideally, you'd be able to choose a date format in a drop down for each label template, such as:

| Date format | Example |
|--------|--------|
| `d/m/yyyy` | 3/8/2022 |
| `dd/mm/yyyy` | 03/08/2022 |
| `d mmm yyyy` | 3 Aug 2022 |
| `d mmmm yyyy` | 3 August 2022 |
| `yyyy-mm-dd` | 2022-08-03 |
| `mm/dd/yyyy` | 08/03/2022
| `mmmm d, yyyy` | August 3, 2022 |

Or perhaps have the above options without separators, with another drop down next to it do choose your separator?
| Separator | Example |
|--------|--------|
| `.` full stop | 03.08.2022 |
| `/` forward slash | 03/08/2022 |
| `-` hyphen | 2022-08-03 |
| ` ` space | 3 August 2022 |

Or if it's simpler, even just a tick box option to match the institution's system date format setting?

**Comment by mgobat** [comment]
This enhancement is available in version v1.3.2-beta2 of the Cloud App. 
To use the beta version:
From the Cloud App Center List, click the “I” icon in the upper right corner of the SpineOMatic tile. Then click the “Try: v1.3.2-beta2” link in the “More information” panel.

"Date options" have been added to the "Other options" section in the layout editor. You may select your preferred date format and date separator character. These options apply to:

- holdings_data.due_back_date
- item_data.arrival_date
- item_data.expected_arrival_date
- item_data.inventory_date
- item_data.weeding_date

**Comment by jonahhighmanUWA** [comment]
Awesome, thank you! This is working as expected. Thanks so much for jumping on it so quickly :)

**Comment by mgobat** [comment]
@jonahhighmanUWA, v1.3.2 is now in general release with this enhancement.
