### ISSUE TITLE
add additional call number parser with regex feature

### ISSUE THREAD

**Issue by berkerY** [ExLibrisGroup/spineomatic-cloudapp#108]
Hi,

we have lots of non-standart call number types at the bonn university library (please see attachment). None of alma call number parser works for us. Therefore we would like to process these special formats with a regex call number parser. 

For example, 
call number: Z4'68/151(7)+1 (left one) => spine label (right one)
![image](https://user-images.githubusercontent.com/5702532/232053589-b0ae9111-aaba-4471-a410-6a2f3950ef28.png)

Regex for this example: 
.replace(/^Z(\d)'(\d{2})\/(\d{3})\((\d)\)\+(\d)$/, "Z $1° $2 ---- $3 ($4) ^$5");

Is it possible to split call number parts into lines and use the parts for adding as field on template? 
call_number_part_1: Z 4°
call_number_part_2: 68
call_number_part_3: / or ----- (a solid line)
call_number_part_4: 151
call_number_part_5: (7)
call_number_part_6: ^1 

Best regards,
Berker

[Etiketten.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/11233071/Etiketten.pdf)

**Comment by berkerY** [comment]
Hi, 
Could you give me any feedback, if it is possible?

Best
Berker

**Comment by mgobat** [comment]
@berkerY, this enhancement is still under consideration.

**Comment by mgobat** [comment]
@berkerY, in the latest version of the SpineOMatic Cloud App, we expose the first 10 individual parts of the parsed call number for inclusion in a label template. Please check that out to see if it helps you in any capacity.

**Comment by berkerY** [comment]
@mgobat the following fields are required for printing labels:

holding_data.call_number
item_data.call_no
item_data.alternative_call_number

Unfortunately, the call number parts in the new version doesn't help us, because the call number must be split using regex.

**Comment by mgobat** [comment]
@berkerY, any thoughts on my comment above? Thanks.

**Comment by berkerY** [comment]
@mgobat Sorry for the late feedback, but i'm trying to build a one regex for all our call number. By the way, i would you ask you, if it's possible to use multiple regex on a call number.

**Comment by mgobat** [comment]
@berkerY, the proposed solution is for one regex applied to the call number per template definition. 

You could have multiple templates supporting different regex, which would require you to know which call number types you are scanning so the correct template could be selected.

**Comment by mgobat** [comment]
First attempt at this enhancement available in the v1.3.6-beta version. To try the beta, click the "i" (information) icon on the SpineOMatic tile in the "Cloud App Center" in Alma, then click the "Try v1.3.6-beta" link.

**Comment by mgobat** [comment]
Available in v1.3.6.
