### ISSUE TITLE
Can't print over 150 items via SpineOmatic.

### ISSUE THREAD

**Issue by Anchi77** [ExLibrisGroup/spineomatic-cloudapp#109]
Hi Support,
853CUM can't print over 150 items via SpineOmatic recently, and it seems that it does not wait until it is successfully loaded and opened, so I can't see the total result. 

I'm not sure if it happened in the AP01 environment. I also checked another environment in AP01 and got the same issue.

If you would like to log in to Alma to check the issue, our workflow is as follows:
Using set name- 金龍圖書_0421
set content number- 337 items

Select a layout- Anchi Test
Select a template- Anchi Test
Offset- 0 

Click "Print 337 labels," and it will open two empty pages.
Please see the link is our situation: https://vimeo.com/820427779/b7f9c3d227?share=copy

Many thanks,
Anchi

**Comment by mgobat** [comment]
@Anchi77, I'm looking into this as a defect, although I haven't been able to replicate it. I've been successful with sets containing 150, 151, and 350 barcodes. I wonder if it is load related....

**Comment by Anchi77** [comment]
Hi, thanks for your reply. I think the issue is because of the region, it happens on AP01.
When I use ExLibris VPN in their environment and do the same thing, and it works. But if I disconnect VPN the same issue still happens.

Please see the link is our situation: https://vimeo.com/820427779/b7f9c3d227?share=copy

**Comment by mgobat** [comment]
@Anchi77, do you have a case opened with Support for this issue? I think that might be a better way to a solution.

**Comment by Anchi77** [comment]
Thanks for your reply. Yes, the case number is 06731862.
Would you like me to transfer the case to Development?

**Comment by mgobat** [comment]
iQuest case closed.
