### ISSUE TITLE
ghost lines

### ISSUE THREAD

**Issue by mck1777** [ExLibrisGroup/spineomatic-cloudapp#11]
I have almost got the app configured. Have one question;

 When I print I am getting lines, gridlines if you will. Like the outline of the cell. How do I get rid of them? I can not figure out where to eliminate them. I have attached a pdf of my 2 templates

[DemcoShort.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6238761/DemcoShort.pdf)
[DemcoTall.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6238763/DemcoTall.pdf)
Would appreciate any assistance to get over my last hurdle.

Thanks
mck

**Comment by MaggieMcGee** [comment]
We are having the same issue as well.

**Comment by jweisman** [comment]
Hi @mck1777 & @MaggieMcGee . We just released a new version which supports disabling gridlines in the [print labels screen](https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#printing-labels).

Let us know how that works for you.

**Comment by mck1777** [comment]
Josh
That is perfect, now to get my horizontal alignment. Awesome thanks for the quick fix.
mck
