### ISSUE TITLE
Is it possible to print label prefixes on multiple lines?

### ISSUE THREAD

**Issue by lizbodian** [ExLibrisGroup/spineomatic-cloudapp#111]
We have a number of label prefixes that we'd like to display on multiple lines.  In the desktop app, this was configured by putting a semicolon between lines: Main;Juv .  Is this possible in the Cloud App?

Thanks,
Liz

**Comment by mgobat** [comment]
@lizbodian, you can put an HTML <br> tag in the text where you wish the line break to be. For example, if you want the label prefix to print as "AA" on the first line and "BB" on the second line, you put "AA<br>BB" as the "Text" field for the label prefix.

**Comment by lizbodian** [comment]
Somehow, when I try to do that, I get a blank label.  Also, it looks to me like the option that's supposed to make the space for the prefix to display if there isn't one isn't working.

**Comment by mgobat** [comment]
@lizbodian, the "Keep label spacing when field empty" option? It is likely that I forgot to implement that option for the label prefixes.  

Could you provide an example of the label prefix which results in a blank label, as well as the source for the label template? You can get the source by editing the template, clicking the "..." in the toolbar, then the "<>" icon.  There might be something in your setup that exposes a problem, as my test handled it correctly: 
<img width="61" alt="labelprefix" src="https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/45852490/af020ab5-8127-44aa-9ab2-06ecea18443b">

My label prefix text is `VFL<br>MDTC`. Admittedly, my test template is pretty simple. 

Thanks.

**Comment by mgobat** [comment]
@lizbodian, just checking in. Did you get this to work for you? Thanks.

**Comment by lizbodian** [comment]
Yes, this seems to work fine, and if I can get the issue in my other ticket
resolved, I will be in great shape, thanks!

-Liz

<http://www.brandeis.edu/library>

Liz Bodian

Metadata Systems Librarian

(781) 736-4645

415 South Street, MS 045 Waltham, MA 02453

Pronouns: she/her/hers

**Comment by lizbodian** [comment]
I can do multiple lines, but I still get blank space if there is no prefix.  Is this fixable?

Thanks,
Liz

**Comment by mgobat** [comment]
Hi @lizbodian...
Unfortunately, in the Cloud App's current design, this is not possible. The extra blank line is due to the `<br/>` tag following the  `{{field:prefix}}` in the template. Any HTML in the template is automatically included in the printed label whether the preceding field has a value or not.

**Comment by lizbodian** [comment]
Actually, I was able to fix it once you phrased it that way.  I just put the break in the prefix template and took it out of the main template.  :)
-Liz

**Comment by mgobat** [comment]
Ha! I thought of that last night when I couldn't sleep. I tried it a bit ago, and it didn't work for me. Glad it is working for you, though! Great job!
