### ISSUE TITLE
Align text top?

### ISSUE THREAD

**Issue by lizbodian** [ExLibrisGroup/spineomatic-cloudapp#112]
I'm running into a problem where I have plenty of room on my spine labels, but the text won't align to the top, so it runs out of room on the label.  This is page 1 of 2, the rest of the call number is on the 2nd page.
![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/77117287/c93160bb-45a3-4957-8947-72df8b25a6b5)
Is there a way to force it to align to the top so I can keep the same font and be able to display the whole call number?    Here's my source code:
<p style="text-align: left;"><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;">{{field:item_data.call_no}}<br />{{field:item_data.description}}</span></p>

Thanks,
Liz

**Comment by mgobat** [comment]
@lizbodian, I think the layout might be the issue. Here's my test result. Labels start printing at the top.

<img width="390" alt="align-top" src="https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/45852490/cd89d4d9-37cb-4b21-914b-582e4f6c7081">

Maybe the details of your layout might help. Could you provide those details? Thanks!

**Comment by lizbodian** [comment]
Sorry, I meant to include that.  I'm using 
<p style="text-align: left;"><span style="font-size: 12pt; font-family: arial, helvetica, sans-serif;">{{field:item_data.call_no}}<br />{{field:item_data.description}}</span></p>

Thanks,
Liz

**Comment by mgobat** [comment]
Hmmm....having trouble replicating the problem. Here're my sample labels:

<img width="196" alt="align-top2" src="https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/45852490/cb35de79-3989-4f90-b8b8-7b26ae902624">

Of course, I don't have the particular label stock, so I have the "Print gridlines" turned on to see the edges of the labels.

Do you have a manufacturer and/or stock number? I may be able to find a Microsoft Word template that might help track down the problem.

**Comment by mgobat** [comment]
@lizbodian, which of the 4 labels on the page you linked to are the ones you are using? None of the measurements seem to match the settings in your layout.

They don't give many details about their labels, and certainly no template to be found. Looking at the 4 labels at that link, it appears that in your layout, you should have values for left margin, page width, label width, label height, and vertical gap. I'm guessing the measurements they provide for the labels are the actual label dimension (label width and label height). So, you would have to take manual measurements for the left margin (the space from the edge of the backing to the start of the physical label), the page width (left-to-right of the full label backing), and vertical gap (space between the bottom of one label and the top of the next). You may have to experiment with the top margin as well, assuming it is the same amount of space (or perhaps 1/2 the same amount of space) as the vertical gap. 

I'm going to reach out to the vendor to see if they have more information that they don't provide on their website.

**Comment by lizbodian** [comment]
Hi Mark,
I think we have the labels on the far right (I'm pretty sure it's 1″ x
1-1/2″ polypropylene labels); I was using cm because it was easier to
measure the gaps.  I'm not in my office this week, but when I go back I'll
try adding all the measurements.  When I did it in the past, it didn't seem
to make any difference, but I'm happy to try again.  I'll tell you how it
goes.  I do have a label on my desk that looks correct, so I need to figure
out how I printed that one.  :)

Thanks,
Liz

<http://www.brandeis.edu/library>

Liz Bodian

Metadata Systems Librarian

(781) 736-4645

415 South Street, MS 045 Waltham, MA 02453

Pronouns: she/her/hers

**Comment by mgobat** [comment]
Okay, let me know how things go next week. I have contacted the vendor, so let's see if I get any additional information, too.
Thanks, Liz.

**Comment by lizbodian** [comment]
OK, I'm now at my desk, and I've changed to inches.  My settings are this:
![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/77117287/67109495-40ba-426e-b36f-3d8ea1fd1439)
My preview in configuration shows 
![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/77117287/f4346a5e-95aa-42fa-a975-c9d4c97c252e)
but when I try to print, I get 
![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/77117287/6b4e15eb-d038-4263-a988-c6ae182ec2e2)
 Any thoughts?
-Liz

**Comment by mgobat** [comment]
@lizbodian, so an improvement over the original image, but still not flush with the top. Let me see what I can figure out. Sorry for the delay in response; was dealing with some other things.

**Comment by mgobat** [comment]
@lizbodian, also what printer are you using? If I can find a publicly available Windows printer driver for it, I can at least install the driver and see what the preview looks like. 

Unfortunately, everything still looks good in the previews with the printers I have available to me. Thanks.

**Comment by lizbodian** [comment]
It's a Zebra ZD621.

Thanks!

<http://www.brandeis.edu/library>

Liz Bodian

Metadata Systems Librarian

(781) 736-4645

415 South Street, MS 045 Waltham, MA 02453

Pronouns: she/her/hers

**Comment by lizbodian** [comment]
Have you had a chance to test this?  We're running out of the old labels and would like to switch printers.
Thanks,
-Liz

**Comment by mgobat** [comment]
@lizbodian, unfortunately I have not. Sorry. I've had my attention on Voyager lately. I'm hoping to get back to Cloud App issues later this week.

**Comment by mgobat** [comment]
@lizbodian, their driver software is too smart; it won't install the driver without the actual printer attached. I'll try a different direction.

**Comment by lizbodian** [comment]
The printer may be too smart as well.  It won't let me change any settings.

<http://www.brandeis.edu/library>

Liz Bodian

Metadata Systems Librarian

(781) 736-4645

415 South Street, MS 045 Waltham, MA 02453

Pronouns: she/her/hers

**Comment by mgobat** [comment]
Hi @lizbodian...

I still am having no luck reproducing the problem. Really makes me think there's something about the printer driver. Could you possibly change to another printer, even the "Microsoft Print to PDF" printer, to see if the labels don't have the empty space at the top with a different printer?

Thanks...

**Comment by lizbodian** [comment]
I changed to marginless printing in the printer settings and that seems to have solved the problem.
Thanks,
Liz

**Comment by mgobat** [comment]
Wow, that's great @lizbodian. Thanks for the update. That setting was added by the Consortium of Icelandic Libraries. Glad it is helping other Alma sites!
