### ISSUE TITLE
Sets or Select Items issue/question

### ISSUE THREAD

**Issue by kronneCSU** [ExLibrisGroup/spineomatic-cloudapp#114]
Hi,

In trying to configure this for batch printing, sets seem to make the most sense since both scanning and selecting only let you do one item (or can't select items from multiple records). However, the set doesn't recognize duplicate barcodes when you need to print two of the same label. Any suggestions for how to accomplish this. For the select method it would be nice to be able to select, save and add from another record so you can build up a batch from multiple titles.

For some context, when we process serial items (magazines) we usually process 16 items from different titles at once (this is due to the label sheets we use). The way serial items arrive, we couldn't wait to process 16 of the same title as that would create a huge back up for us and items wouldn't go out to the shelf in a timely manner. When a title has a supplement, we don't generally make a separate item for the supplement and create two labels from the same barcode. 

Let me know if there is any other information I can provide.

Thanks!

**Comment by mgobat** [comment]
@kronneCSU, you aren't the first person to ask for the ability to have the same barcode in the list more than once. Please see issue #71 for the discussion.

With you permission, I'd like to close this issue and you can add a comment to issue #71.

**Comment by kronneCSU** [comment]
You may close this and I will add my comment to Issue 71, thanks!
