### ISSUE TITLE
Title field issue

### ISSUE THREAD

**Issue by Anchi77** [ExLibrisGroup/spineomatic-cloudapp#116]
Hi Support,

I would like to check about the "title" field, in the article, it mentioned that "Title has special formatting options available. Click the Title dropdown to select any special formatting."
- Specify the number of characters after which the title will be truncated
https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help
![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/129164740/2d4fe918-45a0-43d5-87d9-b60cb6a1127e)

1. It seems we can only use numbers to truncate title?
2. what does the negative number mean in the field?
![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/129164740/8dd93c9b-e24d-460b-8e3e-aa71017e4123)

3. different titles have different numbers. Is it okay to specifically only display $a (245$a or 200$a)?

Many thanks,
Anchi

**Comment by mgobat** [comment]
Duplicate.
