### ISSUE TITLE
Printing call numbers with dividing dots

### ISSUE THREAD

**Issue by Stegewans** [ExLibrisGroup/spineomatic-cloudapp#118]
Hi,

I work at the Koninklijke Bibliotheek of The Netherlands and have a question about printing via SpineOMatic. 
Our call numbers are mainly million numbers. For legibility purposes in the stacks, we want the call numbers to be printed with dividing dots. So for example 14061186 should be printed as 14.061.186
Is this possible? 

Regard,
Lammert Stegewans

**Comment by mgobat** [comment]
Hi @Stegewans. What determines where the dividing dots should be placed in the call number?

**Comment by Stegewans** [comment]
Just the numbering - if it is a milion number.

**Comment by mgobat** [comment]
@Stegewans, this is an enhancement request. To have a full understanding of the requirement for future consideration, which call number field do you include in your label template for which you'd like the decimals included? Thank you.

**Comment by Stegewans** [comment]
Hi! I don't really know how to formulate it, but I will send an image that makes it clear what we want. Regards, Lammert
![Callnumber_with_dots](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/149585375/6bdf1dbd-9b08-4dea-a207-912fc5f64a88)

**Comment by mgobat** [comment]
@Stegewans, does the number have to be at least 1 million in order for the dot to be used or should thousands. too? For example, 123987 should be 123.987?

What should happen if the call number is not numeric only?

**Comment by mgobat** [comment]
Available in release v1.3.6.
