### ISSUE TITLE
Printing call numbers-as-a-barcode

### ISSUE THREAD

**Issue by Stegewans** [ExLibrisGroup/spineomatic-cloudapp#119]
Hi, 
I work at the Koninklijke Bibliotheek of The Netherlands and have a question about printing via SpineOMatic. 

Via our previous library system we printed call number stickers in two lines. On the first line the call number in Arabic numbers was printed, and on the second line the call number-as-a-barcode. We would like to do this via SpineOMatic. Does anybody know how we can print the call number-as-a-barcode? 

Regard, 
Lammert Stegewans

**Comment by mgobat** [comment]
Hi @Stegewans
Is the call number as a barcode stored in Alma, or are you looking to just print the call number using a barcode font?

**Comment by Stegewans** [comment]
Hi! As far as I know, call numbers are not stored as a barcode in Alma. 
We are just looking to print them like barcodes. But what font to choose??

**Comment by mgobat** [comment]
@Stegewans, this is an enhancement request. We would have to add support for the barcode font. Just so we have a full understanding to consider this for a future release, what barcode font would you want to use? Thanks.

**Comment by Stegewans** [comment]
Hi! I don't really know how to formulate it, but I will send an image that makes it clear what we want. Regards, Lammert
![Callnumber_as_a_barcode](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/149585375/ca1faf65-73aa-496f-a455-097e953aa4d9)

**Comment by mgobat** [comment]
@Stegewans, is the assumption that the generation of the barcode does not include the decimals and are display-only correct? Are there any other requirements of the barcode?

**Comment by mgobat** [comment]
First attempt at this enhancement available in the v1.3.6-beta version. To try the beta, click the "i" (information) icon on the SpineOMatic tile in the "Cloud App Center" in Alma, then click the "Try v1.3.6-beta" link.

**Comment by Stegewans** [comment]
Hi @mgobat! Sorry I haven't reacted sooner (private situation going on). We went to Configuration, Call number, chose Deviding Decimals, and added . as Decimal character. And it works! Thank you very much! Regard, Lammert Stegewans

**Comment by mgobat** [comment]
Thank you for the feedback, @Stegewans.

**Comment by mgobat** [comment]
Available in release v1.3.6.
