### ISSUE TITLE
What is the release plan for beta version 1.3.6?

### ISSUE THREAD

**Issue by Bowitz** [ExLibrisGroup/spineomatic-cloudapp#122]
Currently there is a beta version 1.3.6 of SpineOMatic which allows the users to use Reg Exp. For this reason many institutions in the BIBSYS consortium are interested in taking SpineOMatic in use and we would like to know what the plans are for the beta version and when we can expect it to be put in production.

On behalf of the BIBSYS consortium
Gunvald Strømme

**Comment by mgobat** [comment]
@Bowitz, we're glad to hear of your interest in this beta version. It remains in beta simply because we haven't received any feedback on the regex call number parser. Have any of the BIBSYS institutions tried the beta version? Thank you.

**Comment by mgobat** [comment]
Version 1.3.6 released.

**Comment by Bowitz** [comment]
@mgobat, Great, we'll inform the university library in Oslo and the rest of the BIBSYS-consortium.
