### ISSUE TITLE
Misspelling in the configuration Template area

### ISSUE THREAD

**Issue by dancromwell** [ExLibrisGroup/spineomatic-cloudapp#125]
One of our users reported this misspelling in the cloud app Template configuration area and so I am just passing it along.  It is quite hard to notice the error but at the bottom of the Template configuration area there is a check box currently labelled "Keep label spacing when field emtpy" where the word empty is misspelled.  I'm surprised surprised out user even noticed.  Since it was reported though to me I want to alert you of the issue.

Daniel Cromwell
System Specialist Tech Services
Florida Virtual Campus

**Comment by mgobat** [comment]
@dancromwell, yikes, that's embarrassing! It is fixed for the next release.

**Comment by dancromwell** [comment]
@mgobat In terms of currently activated apps will they need to be deactivated and reactivated after the next release to get the corrected text? 

Daniel

**Comment by mgobat** [comment]
@dancromwell, no need to deactivate/reactivate.

**Comment by dancromwell** [comment]
@mgobat OK, thanks for the answer.

Daniel
