### ISSUE TITLE
Enhancement request: Add ability to order templates alphabetically

### ISSUE THREAD

**Issue by kremke** [ExLibrisGroup/spineomatic-cloudapp#126]
Our libraries are using three sizes of labels and for each size there are several template variants, We prefix our templates with L, M and S (for Large, Medium and Small label size) and every now and then we need to add a new template to address some need at one of the libraries.

When creating an new template, Spineomatic appends the new layout to the list of available layouts, it would be great if we could order the list alphabetically so that e.g. all L templates are grouped together, all S templates grouped together etc.

Regards,

Helgi

**Comment by mgobat** [comment]
Alphabetically templates/layouts available in the v1.3.7-beta version. To try the beta, click the "i" (information) icon on the SpineOMatic tile in the "Cloud App Center" in Alma, then click the "Try v1.3.7-beta" link.

Please add feedback/comments to this issue. Thank you.

**Comment by mgobat** [comment]
Available in v1.3.7.
