### ISSUE TITLE
Install Thai Font in SpineOmatic cloud app

### ISSUE THREAD

**Issue by cindywanghui01** [ExLibrisGroup/spineomatic-cloudapp#127]
Hi Mgobat,

We have our first Thailand customer, their Alma will go live in Aug 6 and they'd like to install Thai font in SpineOMatic for their label printing. 
![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/107664965/0fe53f4a-351b-45a0-9661-243dd729c96a)

Could you please contact with Tiny and support our Thai Market? Please do let me if you need any further information from me, thank you!

BR,
Cindy

**Comment by mgobat** [comment]
Support for the TH SarabunPSK font available in the v1.3.7-beta version. To try the beta, click the "i" (information) icon on the SpineOMatic tile in the "Cloud App Center" in Alma, then click the "Try v1.3.7-beta" link.

Please add feedback/comments to this issue. Thank you.

**Comment by mgobat** [comment]
Available in v1.3.7.
