### ISSUE TITLE
Hiding $k when displaying label prefix

### ISSUE THREAD

**Issue by cclavell** [ExLibrisGroup/spineomatic-cloudapp#128]
Some of my call numbers include a $k that show in the catalog, but are printed on the call number label as a different label prefix. Is there a way to choose not to display the $k? At the moment, the prefixes are duplicated.

With no label prefix:
![spineomatic-call-no-test_Page_3](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/171745012/e776bd03-14fb-436e-8f9c-d31987d16737)
With label prefix:
![spineomatic-call-no-2](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/171745012/417f3b63-b3bc-4dab-81e9-c645d28ffa8d)

Also, even though I have "keep label spacing when field empty" unchecked, this does not seem to apply to the label prefix field. It leaves a permanent margin at the top of labels with this field added.

**Comment by mgobat** [comment]
@cclavell, could you provide the code in your template? To get the source code, edit the template, click the "..." button in the toolbar, and then click the "<>" button. This will display the source code for the template. Copy the source code and when you paste it into the comment for the issue, please click the "<>" button and paste the source code between the two ` characters.

Also, please provide a screenshot of your "Label Prefixes" options in the template.

Additionally, a screenshot of Alma showing the call number might be helpful.

Thanks.

**Comment by mgobat** [comment]
@cclavell, also a screenshot of your "Call Number" options for the template. Thanks.

**Comment by cclavell** [comment]
Thanks for your reply.

This is the template I am using:
`<p style="text-align: left;"><span style="font-size: 11pt;"><span style="font-family: 'ala bt courier', courier;">{{field:prefix}}<br /></span></span><span style="font-size: 11pt;"><span style="font-family: 'ala bt courier', courier;">{{field:item_data.call_no}}<br /></span></span><span style="font-size: 11pt;"><span style="font-family: 'ala bt courier', courier;">{{field:item_data.enumeration_a}}<br /></span></span><span style="font-size: 11pt;"><span style="font-family: 'ala bt courier', courier;">{{field:item_data.enumeration_b}}<br /></span></span><span style="font-size: 11pt;"><span style="font-family: 'ala bt courier', courier;">{{field:holding_data.copy_id}}</span></span><br /><span style="font-size: 11pt;"><span style="font-family: 'ala bt courier', courier;"><br /></span></span></p>`

Here are our Label Prefixes (this is not all of them, but enough to cover this example):
![label-prefixes](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/171745012/e1aa0ebb-61cb-4394-844b-58658009c7dd)

Here is the screenshot of the call number in Alma:
![call-number](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/171745012/34c25136-66d2-45f9-9b21-7c05bc51166a)

Here is the 852 for that record.
852	0_ |a TxFK |b KAM |c KIX |h ND3399.F5 |i S534 2011 |k X |t 1

And finally here are the Call Number settings in SpineOMatic - all other fields after these are blank. If it is helpful, we use Parse Routine 5 in Alma for LC.
![call-number-options](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/171745012/6475494d-3bf8-4e01-8098-f48ddc6d07fd)

Thanks!

**Comment by mgobat** [comment]
@cclavell, thanks for the additional details. Based on the provided information, I'm surmising that Alma is telling the Cloud App that the call number is "X ND3399.F5 S534 2011". The Cloud App has no knowledge of which subfields provide each part of the call number. So in the current design, there is no way for the Cloud App to know that the leading X is from subfield k, and should be removed.

What you could try, though, is changing your call number parser in the Cloud App template to be "Reg Ex". Then in the "Call Number Pattern (Reg Exp)" field put "[X]" (without the quotes). This will tell the Cloud App to remove the first uppercase X it finds in the call number. So, in your test case, it should work. The problem, though, is if you have a call number that contains an uppercase X anywhere else but the leading character, it will be removed. So if your call number was "ND3399.F5 X534 2011", it would remove the X in "X534" segment and you'd end up with "ND3399.F5 534 2011" on your label. Does that make sense?

**Comment by cclavell** [comment]
@mgobat so the Call number pattern (Reg Exp) field defines what should be removed from the call number? In that case, what do Call number flags and Call number replacement do? I don't see any of this in the Wiki for the Cloud App.

Deleting all instances of X from the call number definitely isn't going to work; I was hoping for something more precisely located. Even if it's just "anything prior to the first break" or "anything prior to and including the first space". Would something like that be possible?

**Comment by mgobat** [comment]
@cclavell, "Call number flags" are options such as g (global replace) or i (case insensitive). The "Call number replacement" is the string to replace the "Call number pattern".

We would have to add a custom parser to the Cloud App. Any other options besides "anything prior to the first break" or "anything prior to and including the first space" seem appropriate? Or would "Skip X leading segments", where X is a provided number, solve the problem? Do you think such a parser would be useful to Alma users in general, or do you think this is specific to your institution?  Thank you.

**Comment by cclavell** [comment]
@mgobat Skip X leading segments could work, as long as it's clear what those segments are. I'm not sure what other options would be useful, but I was referred to a discussion on ALMA-L that suggests that $k is an issue for other users as well.

Thanks!

**Comment by mgobat** [comment]
Hmmm...so this problem might be better to solve on the Alma side rather than in the Cloud App. We could add a "Skip x segments" option temporarily. But again, the Cloud App doesn't know how Alma is parsing the call number, so it wouldn't know if the first segment was the subfield k, or not.

**Comment by cclavell** [comment]
I think adding a "skip x segments" option would be useful regardless of how Alma is parsing the call number; even if the Cloud App doesn't know it's the $k or some other subfield, the user will. A project like normalizing the $k to match the prefixes displayed on labels across the institutions I'm working with will take some time; allowing users to just skip the first segment of the call number where applicable lets them get back to normal operation post-migration much quicker.

**Comment by mgobat** [comment]
@cclavell, thank you for your input. If the number of segments to skip exceeds the number of segments in the call number, what is the preferred behavior? Don't skip any? Thanks.

**Comment by cclavell** [comment]
@mgobat Yes, I think defaulting to not skip any sounds reasonable. Thanks!

**Comment by mgobat** [comment]
New option to specify "Number of call number parts to skip" available in the v1.3.7-beta version. To try the beta, click the "i" (information) icon on the SpineOMatic tile in the "Cloud App Center" in Alma, then click the "Try v1.3.7-beta" link.

Please add feedback/comments to this issue. Thank you.

**Comment by mgobat** [comment]
Ability to set number of call number parts to skip available in v1.3.7.
