### ISSUE TITLE
Load Barcodes From File

### ISSUE THREAD

**Issue by MaggieMcGee** [ExLibrisGroup/spineomatic-cloudapp#13]
Hi Josh,

The new load barcodes from file is great.

I noticed if you add files from a set and do not print or clear them so they remain saved, if you do a physical items search, you can select items from a physical items repository search in Alma, but items selected using "select items" do not get added to the list of barcodes that were loaded from a file. If you scan in a barcode, the barcode is added to the list of barcodes that were loaded from a file.

Is it intended to work this way? Will it be possible to added items  from select items and be printed with the barcodes loaded from a file? (attaching a file) 

Thanks,
Maggie

https://user-images.githubusercontent.com/81188041/114229189-7a627c80-9945-11eb-9665-06861a0f0f1b.mp4

**Comment by jweisman** [comment]
Hi @MaggieMcGee - thanks for your question. The app currently works such that the selected option (scan, select, set) is what gets printed. We felt that mixing between them would cause inconsistent results and would be more confusing. So if you've selected "Scan", all of the barcodes in the scanned list will be printed. 

Hope that makes sense.

**Comment by MaggieMcGee** [comment]
Hi Josh,

To clarify, the recommendation is to only use one of the options to create a list of barcodes to be printed? Do you mean that if you choose to scan barcodes the next time you go in you cannot add barcodes from a set select items? 

Testing, this all proves to be true, however, you can add a barcode from Scan to a set uploaded from a file. 

Thanks,
Maggie

**Comment by jweisman** [comment]
This is the correct understanding @MaggieMcGee . We tried to add some clarification to the [documentation](https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#printing-labels). Scanning barcodes from a file is part of the scanning option, so the behavior you describe sounds consistent. 

Thanks!
