### ISSUE TITLE
What rolls are needed in Alma to test in the sandbox?

### ISSUE THREAD

**Issue by Mattinthevault** [ExLibrisGroup/spineomatic-cloudapp#16]
We are trialing cloud apps in our alma sandbox and one of our catalogers wants to test this app.  Her error message reads

"No templates or layouts have been configured. Please ask an administrator to configure."

when she tries to use the settings that were already configured for her.

**Comment by jweisman** [comment]
Hi @Mattinthevault . The SpineOMatic app needs to be configured first by an Alma General Administrator. See [here for documentation](https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#configuration) on how to configure. 

Let us know if this works out for you.

**Comment by Mattinthevault** [comment]
We got further than before.  But we were not able to save a "layout" after
several attempts   -Matt

[image: image.png]

**Comment by Mattinthevault** [comment]
Ok, she wasn't pressing enter at the right moment so we *can* save a
layout.  My end user is tracking down what kind of labels we load into our
Zebra.  Looking at it from 10000 feet, I do still find it odd that a GSA is
needed to print a label.  Let's see what happens to her after her new roll
expires.    -Matt

**Comment by MaggieMcGee** [comment]
@Mattinthevault 

How did you configure the cloud app to use a Zebra printer? 

Thanks,
Maggie

**Comment by jweisman** [comment]
Glad you were able to save your configuration.  Note that the admin role is only required for the configuration.  Anyone with resource management roles or fulfillment roles can print the labels.
