### ISSUE TITLE
Regression with saving barcodes

### ISSUE THREAD

**Issue by MaggieMcGee** [ExLibrisGroup/spineomatic-cloudapp#17]
Hi Josh,

There appears to be a regression with barcodes being saved between sessions. I am attaching a recording. I discovered this as I am trying to refine the label setting to align properly.

Thanks,
Maggie

https://user-images.githubusercontent.com/81188041/115063176-388f8400-9eb9-11eb-9b75-d496f0460c35.mp4

**Comment by jweisman** [comment]
Thanks for this report @MaggieMcGee . We indeed were not persisting selected items after pressing "back." This has been fixed in [v0.4.2](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v0.4.2)
