### ISSUE TITLE
Labels shifting to the left after the 3rd label prints. How do I prevent this?

### ISSUE THREAD

**Issue by MaggieMcGee** [ExLibrisGroup/spineomatic-cloudapp#20]
Hi,

I am almost able to print labels. I am having an issue where the 4-8th label begin printing further to the left. How can I prevent this? 

Thanks,
Maggie
![image](https://user-images.githubusercontent.com/81188041/116560981-e181aa00-a8cf-11eb-9f76-9ed7bf4526c5.png)

**Comment by jweisman** [comment]
Sounds like you need to increase the horizontal gap in the layout a small bit. Can you give that a try?

**Comment by MaggieMcGee** [comment]
@jweisman 

Perfect, that worked. 

Maggie

**Comment by jweisman** [comment]
Great!
