### ISSUE TITLE
Add label prefixes for specific combinations of library code/location code

### ISSUE THREAD

**Issue by SWITCHconsortium** [ExLibrisGroup/spineomatic-cloudapp#22]
The windows application for Spine-O-Matic enables us to configure prefixes for specific combinations of library and location. For example, an item held by a library with code MMU and a location code CD will print the prefix AV two lines before the call number begins on the spine label.

Hence this item:
MMU        CD      Call number: 385.26 L548 2002

Will print a spine label like this:

                AV
                
                385.26
                L548
                2002

But this item:
MMU      MAIN    385.26 L548 2002

Will print a spine label like this:

              385.26
              L548
              2002

Is this feature currently under development in the cloud app? Any ETA?

**Comment by jweisman** [comment]
Thanks for reporting this @SWITCHconsortium and for suggestion @tmarnell . We'll see what can be done.

**Comment by jweisman** [comment]
We added an option for label prefixes in the [latest release](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v0.6.0) and to the [documentation](https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#templates). 

Please let us know how it works for you.

**Comment by SWITCHconsortium** [comment]
Thanks for adding in a label prefix option – and so quickly!

I was playing around with the formatting of the labels (left-align, font, font-size), but I am not sure how I would apply those settings to the label prefixes?

***@***.***D74B00.A88A7B50]
If I am missing something obvious, please advise.

Thank you!

Katie

**Comment by jweisman** [comment]
Hi- you're right. It's better to make the label prefix a standard field that can be formatted like all fields. It was now added to the field list- go ahead and insert it into your template and you should be able to format it.

![Screen Shot 2021-05-18 at 19 00 25 ](https://user-images.githubusercontent.com/80420/118685052-6dba2980-b80b-11eb-97a2-7e7c418528bf.png)

Let us know how that works for you.

**Comment by SWITCHconsortium** [comment]
Perfect! This will also satisfy the libraries that like to format the prefix a little differently (e.g. bold, larger font, etc.). Thanks so much – this is perfect for us.

Katie

**Comment by mck1777** [comment]
I am unable to get the Label Prefix option to work. Can you tell me if I am doing anything wrong

[prefix question.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6503805/prefix.question.pdf)

any suggestions? what did I fail to do?

mck

**Comment by SWITCHconsortium** [comment]
In addition to adding the label prefix field in the formatting box, you need to define which library/location combination = a label prefix value in the label prefix section. Happy to send a picture if this does not make sense.

Katie

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mck1777** [comment]
is that not what I did here

![image](https://user-images.githubusercontent.com/72558867/118713332-cc71aa00-b7ef-11eb-9db9-c682a153ac10.png)

**Comment by SWITCHconsortium** [comment]
Sorry – I was looking at the message on my phone and did not see your original pdf.

In addition to setting up the prefixes, you also need to add the new  {{field:prefix}} to the Label contents. This enables you to format the prefix.
***@***.***D74BF8.402EF1F0]

Katie

**Comment by jweisman** [comment]
Glad the feature is useful! And we updated the [documentation](https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#templates) to indicate the label prefix field needs to be added to the template. 

Thanks for the feedback.
