### ISSUE TITLE
Is it possible to use a Zebra printer with spine and piece labels?

### ISSUE THREAD

**Issue by EmeliaS** [ExLibrisGroup/spineomatic-cloudapp#23]
Hi,
I would like to use this with a Zebra label printer, using both spine and piece labels.
I've attached a document with the label sizes etc.
[Label dimensions 2021.docx](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6469681/Label.dimensions.2021.docx)

Is this possible? From what I've seen this only seems to work printing 1 label or to a sheet of labels.
Thanks,
Emelia

**Comment by jweisman** [comment]
Please see [this comment](https://github.com/ExLibrisGroup/spineomatic-cloudapp/issues/6#issuecomment-830815725) from another user on how they set up Zebra printers. Hope this helps.

**Comment by EmeliaS** [comment]
> Please see [this comment](https://github.com/ExLibrisGroup/spineomatic-cloudapp/issues/6#issuecomment-830815725) from another user on how they set up Zebra printers. Hope this helps.

I had seen that, but doesn't help much because its still only prints 1 spine label, not both the spine and piece label. See the document attached to the question to view images of the labels in question. Blank and with an example of what we print.

**Comment by jweisman** [comment]
Hi @EmeliaS - Not sure if this can be done. I'll leave this issue open in case other colleagues have any ideas.....

**Comment by kremke** [comment]
I would be interested in this as well.  The Consortium of Icelandic Libraries is working on migrating our libraries from Aleph to Alma. Most libraries print one label from Aleph containing spine label, barcode and description.  Most libraries would like to continue using this workflow.
![akrav_label](https://user-images.githubusercontent.com/76584888/119641227-f4bd6200-be08-11eb-907c-64e234904946.png)

**Comment by mgobat** [comment]
@EmeliaS, could you share which model Zebra printer you are using?  Thank you.

**Comment by EmeliaS** [comment]
> @EmeliaS, could you share which model Zebra printer you are using? Thank you.

@mgobat It is a GX430t. Thanks.

**Comment by mgobat** [comment]
Thanks for your reply, @EmeliaS.

**Comment by mgobat** [comment]
We've been experimenting with using tables in the "Templates" to support combined spine/piece/pocket label printing. A new version (v0.6.6) was published. We'd appreciate any testing of this feature to see if it supports the diverse label printing needs of Alma users.

Here's a potential solution to the original problem in this issue from @EmeliaS . It may require some tweaking.

Define the template:

1. Add a three column, single row table to the template.
2. Set the width and height of the first column to 22mm and 35mm.
3. Set the width and height of the second column to 7mm and 35mm.
4. Set the width and height of the third column to 73 mm and 35mm.
5. Add the fields for the spine label in the first column.
6. Leave the second column empty; this serves as the gap between the two labels.
7. Add the fields for the piece/pocket label in the third column.
8. Set the border style to "Hidden" for the table and each cell.
9. Save the template.

Define the layout:
 
1. Create a new layout based on "Blank".
2. Set "Measurement units" to centimeters.
3. Set "Top margin" to .3.
4. Set "Left margin" to .4.
5. Set "Page width" to 11.
6. Set "Orientation" to portrait.
7. Set "Label width" to 11.
8. Set "Label height" to 3.5.
9. Set "Horizontal gap" and "Vertical gap" to 0.
10. Set "Labels per page" to 1.
11. Set "Left padding" to .4.
12. Save the layout.

Then use the new template and layout to print your labels.

**Comment by mgobat** [comment]
Curious if anyone has tried using tables in the "Templates" to successfully print spine and pocket labels together. @EmeliaS, were you able to try it? Thanks.

**Comment by EmeliaS** [comment]
> Curious if anyone has tried using tables in the "Templates" to successfully print spine and pocket labels together. @EmeliaS, were you able to try it? Thanks.

@mgobat We aren't back on campus yet, so when I have access to the printer I will test this. It looks promising!

**Comment by mgobat** [comment]
@EmeliaS, we look forward to your test results. I will close this issue. Please open new GitHub issues for any problems you experience using tables in the templates. Thank you!

**Comment by mgobat** [comment]
@HSteeleLTS, please open a new issue. Are your label requirements exactly as in the example? If not, please include the template and layout settings in the new issue.
