### ISSUE TITLE
Other user cannot edit SpineOmatic configurations

### ISSUE THREAD

**Issue by MaggieMcGee** [ExLibrisGroup/spineomatic-cloudapp#25]
Hi,

Why am I able to edit configurations, but another user cannot?

Thanks,
Maggie

<img width="223" alt="Spine_cant_edit" src="https://user-images.githubusercontent.com/81188041/121035439-e150b600-c77b-11eb-9da9-c50a1f0784ff.png">

**Comment by jweisman** [comment]
Hi @MaggieMcGee . Configuration is only open to users with the General Administration role in Alma.

**Comment by MaggieMcGee** [comment]
Thanks Josh! Missed that piece of information. That is great! Also, I found if I make changes, it makes changes to every user using SpineOmatic. Is this correct, changes are inherited by other uses who install the App.

Thanks,
Maggie
________________________________
