### ISSUE TITLE
Suppress blank label prefixes

### ISSUE THREAD

**Issue by cpham21** [ExLibrisGroup/spineomatic-cloudapp#28]
We have label prefixes triggered for only a few locations and have it listed before our call numbers. 

![Screen Shot 2021-07-06 at 11 39 59 AM](https://user-images.githubusercontent.com/87029685/124629773-bf685300-de4f-11eb-90b5-65d5267963d0.png)

There is a blank line on our labels whenever the prefix is not triggered. Would it be possible to suppress that space so the call number and the rest of the label is moved up when it is printed? 

Thank you!

**Comment by jweisman** [comment]
Thanks for your issue. We'll look into this.

**Comment by jweisman** [comment]
Hi @cpham21 - we released a new [version](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v0.6.5) which should fix this.
