### ISSUE TITLE
Please add Arial Narrow and more odd font sizes

### ISSUE THREAD

**Issue by SWITCHconsortium** [ExLibrisGroup/spineomatic-cloudapp#29]
Would you be willing to add Arial Narrow to the font options as well as odd sizes 13 and 15

**Comment by jweisman** [comment]
Hi @SWITCHconsortium - we released a new [version](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v0.6.5) which adds these options.
