### ISSUE TITLE
Add "Start printing labels at" option

### ISSUE THREAD

**Issue by YoelKortick** [ExLibrisGroup/spineomatic-cloudapp#3]
This came from McGee, Margaret Margaret.McGee@suny.edu
She is seriously testing the SpineOMatic Cloud App and I am working closely with her.

Maggie staes:
We really need a "Start printing labels at" option so we can reuse sheets of labels. Typically, a full sheet is not always used when printing spine labels. Libstick and SpineOmatic both have this.

**Comment by mattzman** [comment]
My library would also love to see this feature implemented ASAP. We frequently print small batches or one-off labels.

Thanks!

Matt Z

**Comment by jweisman** [comment]
Thanks for the feedback. We will try to add this feature in the near future.

**Comment by MaggieMcGee** [comment]
Tested "Offset" in the latest version. So excited we can pick which label to start at. Thank you!

**Comment by jweisman** [comment]
Indeed @MaggieMcGee - we just released a [new version](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v0.1.0) which includes this feature. Glad it helps!
