### ISSUE TITLE
 Spinomatic is cutting last line of topographic

### ISSUE THREAD

**Issue by TBESC** [ExLibrisGroup/spineomatic-cloudapp#30]
Dear all,

We are testing SpineOMatic App to print call number labels in our Library. We use LCC call numbers with the parsing routine nr. 5 in Alma. We have tried with the font Courier New and 12pt, to print in labels Apli 01712.
The print is ok if the call number has 4 lines, but if it has 5 lines, the last one is cut, while at the top of the label there is still free space.

The layout is this one:
Measurement units: centimeters
Top margin: 0
Left margin: 0
Page width 21
Orientation: portrait
Label width 7
Label height 2.6
Horizontal gap: 0
Vertical gap: 0;
Labels per page: 33
Left padding: 0
In the old system (Sierra) we were printing with the same font and labels and there were no problems.

![imatge](https://user-images.githubusercontent.com/87298975/125244994-4ace6200-e2f0-11eb-9372-86fcf9e3a26d.png)

Is there any way to adjust it?

**Comment by mgobat** [comment]
@TBESC, curious if the latest updates helped with this problem.  Thanks!

**Comment by TBESC** [comment]
Yes, now it's working
many thanks1

*Antoni Borràs i Escorihuela*
/Gestor de projectes/

Unitat de Projectes
Servei d'Informàtica

Pl de la Mercè 10-12 | 08002-Barcelona
[Tel.] (+34) 935 421 274
***@***.***

[image: Universitat Pompeu Fabra, Barcelona]


Missatge de mgobat ***@***.***> del dia dj., 11 de nov. 2021
a les 19:44:
