### ISSUE TITLE
Add support for specifying barcode size

### ISSUE THREAD

**Issue by jweisman** [ExLibrisGroup/spineomatic-cloudapp#31]
Support specifying the size of the barcode in templates.

Internal reference URM-157550

**Comment by mgobat** [comment]
We've released version, v0.7.0. 

Two new fields, "Barcode width" and "Barcode height", may be set in template configuration. If "Show as barcode" is checked, these two fields may be edited (just like the existing "Barcode encoding" field).

If values are not provided, the "Barcode width" will be set to 1 and the "Barcode height" will be set to 20 when the barcode is printed.

If "Show barcode value" is checked, the barcode value will now print in the selected font size.

If you test this new feature, please add feedback/comments to this issue.  Thank you!
