### ISSUE TITLE
Additional call number parser

### ISSUE THREAD

**Issue by ling-jiang-exl** [ExLibrisGroup/spineomatic-cloudapp#32]
From SF Case 00982739, the customer wants to manipulate the call number before printing it out.
Shelving info saved in the holding record 852$$j field is printed out as part of the call number unexpectedly.
If Regex feature is supported, we can filter the irrelevant shelving info out from call number.

For example, the customer may have a call number like 'X24 /E 14 第119排B面'.
They would like to apply 'X24 /E 14 第119排B面'.match(/^[\w\s]*\/[\w\s]*/gm) and get "X24 /E 14 " as the result.
However, use the method above in Label Contents only get all function and Regex printed out as text.

**Comment by jweisman** [comment]
Hi @ling-jiang-exl - we're supporting custom call number parsers (see the [docs](https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#templates)). So we can add one for this customer if none of the [Alma parsing methods](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/Physical_Resource_Management/070_Configuring_Resource_Management/060_Configuring_Call_Number_Parsing_when_Printing_Labels) work for them.

Please take a look at the OLH in the above link. If none work, let us know what parsing method they'd like. The regex provided doesn't provide the desired results when I run it in a regex parser.

Thanks.

**Comment by ling-jiang-exl** [comment]
Hi Josh,

Thanks for your reply and provided information about call number parsers.
There are many ways to parse the call number, however, the customer only wants part of the original call number.
It means removing or replacing part of the call number, or return some matched part of it but not only split it.

At present, the customer is using parsing call number routing #3
I have tested the Regex (/^[\w\s]*\/[\w\s]*\b/g) which works fine for the call number
"X24 /E 14 第119排B面" > "X24 /E 14"
Please see attached screenshot of the testing result from Regex101

Regards,
Ling

**Comment by jweisman** [comment]
We added the "remove shelving info" parser to the [latest release](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v0.6.7). Please leet us know how it goes.

**Comment by ling-jiang-exl** [comment]
Hi Josh,

Thanks for your update to the app.
Remove Shelving Info parser works well.
However, could you add the Split by Slash feature to Remove Shelving Info parser.
Or can you make the parser be multi-selectable as checkbox options?
Because the customer need the feature of both of the parsers.

Thank you.

Ling

**Comment by jweisman** [comment]
Updated the removing shelving info parser to split by slash.
