### ISSUE TITLE
Request to further modify the Call Number Parser

### ISSUE THREAD

**Issue by ling-jiang-exl** [ExLibrisGroup/spineomatic-cloudapp#34]
Hi Team,
Please modify the current Call Number Parser of Remove Shelving Info:
From "^[\\w\\s]*\\/[\\w\\s]*\b" To: "[0-9A-Za-z[:space:]\\/\\.\\:\\(\\)\\+\\#\\-]+"
Because the current one cannot handle the call numbers:

> I313.45 /73 第47排B面
> Z5 /1(2010) 第5排B面
> TB472-39 /4 第22排B面
> TP303 /E 18:2.v1 第3排B面
> TP312C# /E 1 第7排A面
> TP312C++ /1 第27排A面

FYI, this is the relevant issue with #32 
Thank you.
Ling

**Comment by kremke** [comment]
Would it be possible to have two call number fields, one as a parsed call no and another without the parsing?  I need to design a label that prints the parsed call number on a sub-label and then again as one line on the pocket label.  I haven't been able to figure out how to access both versions on the same label.

Regards,

Helgi

**Comment by ling-jiang-exl** [comment]
Hi Team,
Per testing from the customer, they have some symbols such as . and - in call numbers, which are not covered by the current regex [\w\s]. So, please kindly update the regex for "Remove Shelving Info" parser to [\w\s.-] so we can ask the customer to perform another round of testing.
Thank you.
Ling

**Comment by ling-jiang-exl** [comment]
> Would it be possible to have two call number fields, one as a parsed call no and another without the parsing? I need to design a label that prints the parsed call number on a sub-label and then again as one line on the pocket label. I haven't been able to figure out how to access both versions on the same label.
> 
> Regards,
> 
> Helgi

Hi Helgi,
I think it is not possible to refer to the same call number by apply different parser on them respectively. At present, as far as I can see, the parser applies to all call numbers. I think you may create a new issue for asking for a way to bypass the parser using some special syntax in the referring code.
Regards,
Ling
