### ISSUE TITLE
Copy # formatting

### ISSUE THREAD

**Issue by brimoore-SDSU** [ExLibrisGroup/spineomatic-cloudapp#37]
The desktop version of SpineOMatic has some useful format coding options, particularly for copy_id (attached)
![image](https://user-images.githubusercontent.com/89492416/130874673-78baeadb-36bf-41db-ab51-2e293b4acea7.png)

**Comment by jweisman** [comment]
Hi @brimoore-SDSU - I'm going through some older issues and I wanted to check to see if this was still relevant.

Can you provide some more details here- we have some capabilities to offer custom call number parsers, but I would need to know what specific features around copy number you'd like interested in.

Thanks!

**Comment by brimoore-SDSU** [comment]
Hello Josh,

Specifically we use the control "*" suppression code to prevent printing #'s < 2.

Thanks,   Brian

**Comment by jweisman** [comment]
Thanks @brimoore-SDSU - we'll see what can be done.

**Comment by mgobat** [comment]
Added in release v.1.1.9.
