### ISSUE TITLE
Automatically print spine info

### ISSUE THREAD

**Issue by chilurean** [ExLibrisGroup/spineomatic-cloudapp#38]
Hello,
 I have GA access for the SpineOMatic, which is great for modifying the way the info on the spine label is printed.  The issue I'm having is being able to automatically print the info once I scan the item without being asked to choose a template.  I'm having to manually type in the information for every item I scan.  I was able to do this before I was granted GA access, but not since.  Did I accidentally delete something on my end?

**Comment by jweisman** [comment]
Hi @chilurean - thanks for your question. Not sure I understand 100% the issue. Can you perhaps add a screenshot which shows what you're seeing?

Thanks!

**Comment by mgobat** [comment]
@chilurean, are you still experiencing this problem? If so, could you please provide a screenshot of what you are seeing?  Thanks.

**Comment by mgobat** [comment]
Closing this issue. Please open a new issue if it is still a problem.
