### ISSUE TITLE
Allow non-administrators to Create/adjust templates & layouts (Configurations)

### ISSUE THREAD

**Issue by VangelisPalaskas** [ExLibrisGroup/spineomatic-cloudapp#42]
Hi Ex Libris community,

As I have been very active in using the SpineOMatic cloud app it came under my attention that there is an issue in the configuration of the templates and layouts and the user rights.

Accordingly, my institution would like to give rights to non-admin accounts to create and/or adjust the templates and layouts. However, based on the ['Configuring Cloud Apps'](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/050Administration/050Configuring_General_Alma_Functions/Configuring_Cloud_Apps) documentation we need to provide full system admin rights to 'third users' in order to create and/or adjust the templates and layouts. 

At this moment, this is crucial because some label printing tests need to take place remotely. This means that institutions need to be able to adjust the template and layout options (e.g. label height & width) according to their printing device. At the same time, it seems a bit odd to provide full system admin rights to users in order to perform this action but maybe there is something that I am not fully aware of. 

Do you have any suggestions regarding this issue?

*Note: I have noticed that in other applications, those configurations could be changed through the 'Settings'. According to the 'Configuring Cloud Apps' documentation, this means that the 'third users' do not need necessarily to be full system admins. Could the 'switch' of the templates and layouts from 'Configurations' to 'Settings' be a potential option?   
<img width="1642" alt="Configurations" src="https://user-images.githubusercontent.com/89778038/131657662-40b70f7f-121f-440f-80d6-9cd344683117.png">

**Comment by jweisman** [comment]
Hi @VangelisPalaskas - thanks for your issue. Cloud Apps provide the option for "settings" or "configuration." Settings are user-based, while configuration applies for the app institution-wide. The SpineOMatic Cloud App uses the configuration, as it doesn't make sense to have each user define all of the templates and layouts individually.

Configuration is available only to users with the general-admin role, hence the issue you're seeing. We can consider requesting a general change in the Cloud Apps framework to allow non-admins to access general configuration. If we were to do that, what roles do you think would be appropriate for SpineOMatic configuration?

Thanks

**Comment by VangelisPalaskas** [comment]
Dear @jweisman - many thanks for the reply. Overall, the most convenient solution would give the minimum amount of rights to a user in order to perform the modifications in the templates & layouts (Configuration) without affecting other spheres of permissions. 

Thus, ideally, a new 'Label Printing Configurator' role could solve the issue. Alternatively, those rights could be added to an existing role such as the API Label Printing Read (albeit not read only).

It is true that for now our main focus is on SpineOmatic, and hence accessing configurations might have different implications in the future changing from one Cloud App to another. However, it seems very important for the time being to have this role and we are very thankful that you are looking into this issue.

I hope my answer helps. As I have mentioned the other alternative that I was thinking was to switch those options from 'configuration' to 'settings'. Just to be a bit more specific, I had the Orbis example in mind. 
<img width="201" alt="Settings" src="https://user-images.githubusercontent.com/89778038/132318734-9dfc66b2-c85b-400c-a7f4-1cfc050fb433.png">
  

Of course, the most appropriate choice is up to your own judgement in which I am very confident.

**Comment by jweisman** [comment]
Thanks- we'll think though this a bit.

**Comment by jweisman** [comment]
Hi @VangelisPalaskas - I'm happy to update that we've [released a new version](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v1.1.6) which allows configuration for users with the Catalog Administration role in addition to the General Administrator role. This works in the December release, so it can be tested now in the Sandbox. There is a new button on the main screen:

<img width="402" alt="Screen Shot 2021-11-23 at 13 35 06 " src="https://user-images.githubusercontent.com/80420/143017383-f348d475-6d1d-4969-aafd-99971dbdd86a.png">

Note though that we ran into a small issue. In the December release this will only work if the user also has the ability to view user details. So they'll need an additional role such as User Manager or Circ Desk Operator.  

Let us know how that works for you.

**Comment by VangelisPalaskas** [comment]
Hello Josh. I am also very happy with the new version. The delegation of configurations to non-admins will help us roll out the user testing phase. 

For now there is no problem that the Circulation Desk Operator needs to be simultaneously active. I will let you know if something changes in the future. 

Thank you again for looking into this rather more complicated case. It was an important issue for us.

**Comment by jweisman** [comment]
Great to hear. Thanks for the feedback.

**Comment by jweisman** [comment]
Hi @VangelisPalaskas - just an FYI. In [v1.1.7](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v.1.1.7) we removed the limitation around Circulation Desk Operator. Now it should work for anyone with the Catalog Administrator role, regardless of any other roles.

**Comment by VangelisPalaskas** [comment]
Hi @jweisman. This sounds good. Thank you very much for letting me know.
