### ISSUE TITLE
Author/Main Entry information for pocket labels?

### ISSUE THREAD

**Issue by grimmerr** [ExLibrisGroup/spineomatic-cloudapp#47]
Our pocket label practice has been to include a line for Author/Main Entry. These fields were available in the old desktop version of SpineOmatic. Are these fields available in the cloud app? I didn't see them as an option.

**Comment by jweisman** [comment]
Hi @grimmerr - thanks for your question. Can you try adding this to your template? If it works we can add it to the drop-down menu as well.
```
{{field:bib_data.mms_id}}
```

Let us know how it goes.
