### ISSUE TITLE
Save a set of barcodes for printing

### ISSUE THREAD

**Issue by MaggieMcGee** [ExLibrisGroup/spineomatic-cloudapp#5]
The ability to save a set of barcodes to print at a later time, known as batches. Batches of barcodes can be saved before closing the app and they can be opened, edited, and printed at a later time.

Currently, when the app is closed, the barcodes are not save in the apps history so the user can return and continue adding barcodes to be printed at a later time. The user would have to rescan all the barcodes that were lost when the app was closed, plus add additional barcodes.

**Comment by jweisman** [comment]
We're now saving scanned barcoded between SpineOMatic sessions. Scanned barcodes are cleared after successful print or when clicking the Clear button in the main screen. Hope this resolves this issue.

**Comment by MaggieMcGee** [comment]
Hi Josh, 

I have not been able to successfully do this. What is the workflow you are using? I tried canceling a print and then doing another search.  Selecting barcodes to print and doing another search to select barcodes and only the current barcodes show and print.

Is there a way to create a set that can be named and then retrieved to continue adding barcodes to be printed?

Thanks,
Maggie

**Comment by jweisman** [comment]
Hi Maggie. We were trying to cover the use case where librarians will scan several barcodes, leave and return to the app, and the scanned barcodes will persist. See the screen capture below:
![persist-barcodes](https://user-images.githubusercontent.com/80420/113160676-5b2d6600-9246-11eb-938d-80c67d7370b0.gif)

I don't think we want to reproduce set capabilities in the app as we want to rely on sets created in Alma which can be selected in the app. 

If this doesn't cover your use case can you describe which case you're trying to address?

Thanks!

**Comment by MaggieMcGee** [comment]
Hi Josh,

Thank you for the workflow. To clarify, saving will only be an option when a user scans in the barcodes, not from searching physical items and selecting the items to be printed. 

Will this be available if you do a physical items repository search and select the barcodes to be printed?

I understand not wanting to replicate creating sets in Alma.

Thanks,
Maggie

**Comment by jweisman** [comment]
Hi Maggie. We added the persistence for the scanned barcodes as we understand how a session might be interrupted and would be cumbersome to re-scan all of the barcodes. 

Do you see it as a common scenario where items are selected from a list of search results and then the session is interrupted? Do you think that case should be persistent as well?

**Comment by MaggieMcGee** [comment]
Hi Josh,

I asked and scanning barcodes would be the typical workflow, so maybe not necessary to save sets of records.

Thanks.
Maggie
