### ISSUE TITLE
Templates & layouts text field search - Enhancement

### ISSUE THREAD

**Issue by VangelisPalaskas** [ExLibrisGroup/spineomatic-cloudapp#52]
Dear Josh,

Our configuration phase with the KU Leuven libraries will gradually come to its end with the valuable solution that Ex Libris has provided regarding the roles. 

Currently, our intention is to proceed in a user testing phase. However, since KU Leuven has around 14 libraries thus around 35-50 layouts/templates. To that end, a user-friendly way for the searchability of the SpineOMatic layouts and templates would be very valuable. 

Thus, would be to ask for the option of a '_text field_' in the '_Select a layout_' and '_Select a template_' sessions in addition to the current option of the '_choice/drop-down list_'. The existing 'Label Prefix' library search field is a great example.

With this enhancement we hope that the users can start typing a keyword and that the cloud app matches the input with the existing layout/template names in a case insensitive way. Would you be able to provide us with that enhancement?

<img width="918" alt="Label Prefix - Add Text Field" src="https://user-images.githubusercontent.com/89778038/139091950-fb500e70-d35c-43ac-979f-adce2e34abdb.png">

On top of the 'text field' we will establish an 'internal' filing system for the names of the layouts/templates albeit the '_text field_' seems quite important. 

Please feel free to recommend other solutions if any. We know that until recently we asked Ex Libris for other enhancements so we understand if this is not a direct priority. Nonetheless, it will solve an issue for an complex of libraries.

Thank you in advance,

Kind regards,

Vangelis Palaskas.

**Comment by jweisman** [comment]
Hi @VangelisPalaskas - in the [latest release](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v1.1.3) we have added auto-complete to the layout and template selection in the print screen. Let us know how it works for you.

**Comment by VangelisPalaskas** [comment]
Hi @jweisman. From a quick testing, I have noticed that if a name contains spaces those are not retrievable in the user's search unless they are replaced with an underscore ( _ ) (e.g. the user has to type 'T1_Default_Template' for a template named 'T1 Default Template').  Therefore, I will focus on a filing system without spaces. I might or might not come back to you in the future about this.

However, it is a functional solution and something that we can definitely work with! 

Thanks a lot for the hard work and the support!

**Comment by jweisman** [comment]
Hi @VangelisPalaskas - thanks for the feedback. We've pushed a change which should allow you to search a term with spaces as well. Hope this helps.

**Comment by VangelisPalaskas** [comment]
Thank you very much Josh!
