### ISSUE TITLE
Call Number Parse Routine - Enhancement

### ISSUE THREAD

**Issue by VangelisPalaskas** [ExLibrisGroup/spineomatic-cloudapp#53]
Dear Josh,

After the launch of the User Testing phase we have picked up some minor necessary enhancements that we want to tackle step by step.

One of our priority issues, is providing an efficient 'Parse Routine' to fully automate the 'line breaks'  of the Parsed Call Number. Currently, no Alma Parse Routine seems suitable for this action. We have identified 'Parse Routine 3' as one of the closest to our desired outcome since it is parsing mainly based on [spaces].  

Our issue is that we would like a parse routine that takes into account only the sub-fields of each field/cell to introduce the line breaks on the printed labels.Case in point, the ‘852 - Location field’ in the Holdings Call Number and particularly the sub-fields ‘$$h, $$i, $$k, $$m etc. Please see the screenshot for examples.

Thus, could you please provide us with a Parse Routine that parses only the sub-fields (and not the spaces) of each Holdings Call Number Cell? 

<img width="933" alt="Line Breaks Explanation Alt" src="https://user-images.githubusercontent.com/89778038/141456404-0a2e5c88-09f8-4475-83c5-0f3011e0c478.png">

I have experimented with all Alma Parse Routines and I have addressed a question to the libraries to simply remove the [spaces] but apparently they are quite meaningful for them in some cases... Moreover, I have noticed that you have successfully provided other Parse Routines in the past so adding another parser in SpineOMatic would be very useful for us.

Please let me know if there are any questions.

Kind regards,

Vangelis Palaskas.

**Comment by jweisman** [comment]
Thanks for the suggestion @VangelisPalaskas . We'll look into this.

**Comment by jweisman** [comment]
Hi @VangelisPalaskas . The [latest release](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v1.1.5) of SpineOMatic includes this new call number parser. Let us know how it works for you.

**Comment by VangelisPalaskas** [comment]
Hello @jweisman. Many thanks for the prompt response. 

I have tested the call number parser today and it works perfectly!

**Comment by jweisman** [comment]
Glad to hear : )
