### ISSUE TITLE
Spacing Format Tool (Enhancement)

### ISSUE THREAD

**Issue by VangelisPalaskas** [ExLibrisGroup/spineomatic-cloudapp#54]
Dear Josh,

I hope that you are well. This is one of our minor issue regarding the spacing between the fields of the templates. The reason why spacing has been an issue is because we cannot accommodate a 4th line in the labels without substantially decreasing the font of the fields. Please see the example below.

I have tried also to use a table in the template but it doesn’t seem to work for our case.

Would you be able to provide us with one of the following enhancements:
1.	Ideally: Option to adjust the spacing between the template's fields or;
2.	Alternatively: Reduce the default spacing to the minimum.

<img width="958" alt="Spacing Issue Explanation" src="https://user-images.githubusercontent.com/89778038/144446056-7d77ffa6-57ad-4847-af1c-3d68fad5653e.png">

This is not a priority issue so we will understand if it takes some more time. However, it would be a step closer to cover as many existing use cases as possible.

Please feel free to contact me if something is unclear. Thank you again for the awesome support!

Kind regards,

Vangelis Palaskas.

**Comment by jweisman** [comment]
Hi @VangelisPalaskas - thanks for your question. If I understand your template correctly, you have a new line after the _BTAB_. Can you try doing a _shift/return_ after the _BTAB_ instead of a regular _return_. That should put the next line directly without any space.

**Comment by VangelisPalaskas** [comment]
Hi @jweisman. Indeed, it works as expected!

Thanks a lot for answering my (rather silly) question.
