### ISSUE TITLE
[URGENT] Call Number Parser - Default (Alma) does not work after changing Label Content

### ISSUE THREAD

**Issue by ling-jiang-exl** [ExLibrisGroup/spineomatic-cloudapp#55]
Hi Team,

This is an urgent issue, please kindly handle with priority.
After changing the Label Content from a field to another, the Call Number Parser does not work anymore.
It means, despite there is nothing else changed, the printed call numbers do not break lines anymore.
Even restore the selected field for Label Content to the original one does not have the issue resolved.

Please check if this is a bug or something and handle with priority.
This issue is replicated in both PROD and PSB environment for the customer 86WKU.

Regards,
Ling

**Comment by jweisman** [comment]
Hi @ling-jiang-exl - I'm sure sure I understand the issue. Can you provide steps to reproduce it?

**Comment by ling-jiang-exl** [comment]
Hi @jweisman - Thanks for your reply.
The current printing result is:
```
DS796.W46
.Y89 2019
CN
```
Please see the following screenshot for the current printing result:
https://www.screencast.com/t/F3sTsK3710ec
While the expected result should be like:
```
DS
796
W46
Y89
2019
CN
```
The issue means the in app defined Default (Alma) call number parser does not work.
See the following screenshot for reference to the in app configuration:
https://www.screencast.com/t/BsIJQBQbd

**Comment by jweisman** [comment]
Hi @ling-jiang-exl - can you confirm which Alma parser is configured? See the OLH referenced from the "call number" section of the [Template Configuration documentation](https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#templates).

**Comment by kyooryoo** [comment]
Hi @jweisman I confirmed in the customer's PROD that they are using Call Number Parser Routine 7 which was configured since 13th Aug, 2021 without change since then.

**Comment by jweisman** [comment]
Hi @kyooryoo - thanks for confirming. Let's review the remainder of the configuration. 

Call number parsing configuration:
![Screen Shot 2021-12-28 at 15 23 02 ](https://user-images.githubusercontent.com/80420/147570630-74f1f60e-8e36-42ed-982b-3907f122f5d6.png)

Template configuration:
![Screen Shot 2021-12-28 at 15 23 53 ](https://user-images.githubusercontent.com/80420/147570745-2b515861-2ffd-455f-a5ef-1737ba90a188.png)

Item with call number of proper type:
![Screen Shot 2021-12-28 at 15 22 07 ](https://user-images.githubusercontent.com/80420/147570801-41e59daa-d53f-452b-955e-292b8ecc0daa.png)

Print label, call number breaks on periods:
![Screen Shot 2021-12-28 at 15 22 20 ](https://user-images.githubusercontent.com/80420/147570839-efb12ebd-2595-44b8-9db8-8c05f50d9d77.png)

Please let me know if your configurations looks the same. If so, let me know the environment (sandbox/production) and customer code/name, along with a barcode we can test with.

**Comment by ling-jiang-exl** [comment]
Hi @jweisman Thanks for your information. The customer was using {{field:holding_data.call_number}} but not {{field:item_data.call_no}}. I see {{field:item_data.call_no}} could be chosen from "Parsed Call Number" as one of the "Add field" dropdown list option. This case could be closed.
