### ISSUE TITLE
[Enhancement] Adding logic to selecting fields for Label Content

### ISSUE THREAD

**Issue by ling-jiang-exl** [ExLibrisGroup/spineomatic-cloudapp#56]
Hi Team,

This is an enhancement request from the customer 86WKU.
They want to add logic into choosing the field for Label Content such as:
* if item call number is null use holding call number
* if item call number is longer than holding call number, use item call number.
Please kindly evaluate the requirement and let me know if there is a plan.

Regards,
Ling

**Comment by jweisman** [comment]
Hi @ling-jiang-exl - we can implement this as a call number parser. However, I need some clarification on the requirements. The first requirements states that if the item call number is null, we should use the holding call number. If the item call number is not null, you would like to use it. So the second requirement seems unnecessary. 

Do you agree?

**Comment by jweisman** [comment]
We added the parser as we understood it to [v1.1.7](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v.1.1.7). Please let us know if this addresses the issue.

**Comment by ling-jiang-exl** [comment]
@jweisman Thanks for your update. Are you talking about the Call Number Parser of "Holding Call Number"? What field should be chosen, {{field:item_data.call_no}} or {{field:item_data.alt_call_no}}? The requirement is using Item Call Number if it exists, otherwise use Holding Call Number. I tested with choosing {{field:item_data.alt_call_no}}, which takes the Item Call Number, and the parser of Holding Call Number, which I hope can take the holding call number if item call number does not exists. However, the result is the same as before, since the item which does not have item call number still has a blank call number in the print result.

**Comment by jweisman** [comment]
Please try it with `{{field:item_data.call_no}}`.

**Comment by ling-jiang-exl** [comment]
The field {{field:item_data.call_no}} and the parser Holding Call Number does not have the requirement fulfilled.
The printed result is still the Holding Call Number, despite there is Item Call Number exists.

Today, I have received the same request from another customer 86CUHKSZ, which is:
If the Item Call Number exists, print it. Otherwise, print Holding Call Number.

**Comment by ling-jiang-exl** [comment]
Update to the requirement from 86CUHKSZ:
Check if holding_copy_id exist, if it exists as XX, add "c. XX" under the current call number.
If the above requirement get fulfilled, we can propose it as a workaround for 86WKU.

**Comment by ling-jiang-exl** [comment]
Update to the requirement from 86CUHKSZ:
Check if holding_copy_id exist, if it exists as XX, add "c. XX" under the current call number.
If the above requirement get fulfilled, we can propose it as a workaround for 86WKU.

**Comment by jweisman** [comment]
I think we understand the field mapping now. The "item call number" in the UI:
![Screen Shot 2022-01-16 at 12 44 34 ](https://user-images.githubusercontent.com/80420/149663614-5c53eba0-eae5-451b-a78d-9b081299a2a4.png)

Is mapped to the "alternative_call_number" in the API.

So in the [latest release](https://github.com/ExLibrisGroup/spineomatic-cloudapp/releases/tag/v1.1.8) we renamed the call number parser to "item_call_number" and use it if it exists:
![Screen Shot 2022-01-16 at 16 11 42 ](https://user-images.githubusercontent.com/80420/149663648-1950e4fd-dacb-4f90-9050-591d1067273f.png)

Hope this helps.

**Comment by mgobat** [comment]
@ling-jiang-exl, can you confirm if this is working as desired now? Thanks.

**Comment by dongchch2016** [comment]
Hi @mgobat ,
Ling jiang has left our company in February.
I checked the code and made some updates for this issue. Please review the code and please let me know if there's a question.

Thanks,
chenchen

**Comment by mgobat** [comment]
@dongchch2016, this week, hopefully. One of the changes you checked in, reordering the scanned in barcodes, isn't working correctly. I have a fix for that, and I'm testing it today.

**Comment by mgobat** [comment]
Available in latest release, v1.2.6.

**Comment by dongchch2016** [comment]
Great!!! Thank you!

chenchen
