### ISSUE TITLE
[enhancement] request to add Microsoft Yahei font and 16pt and 17pt font size options

### ISSUE THREAD

**Issue by ling-jiang-exl** [ExLibrisGroup/spineomatic-cloudapp#57]
the customer 86CUHKSZ request to add Microsoft Yahei font and 16pt and 17pt font size options

**Comment by VangelisPalaskas** [comment]
Question for @mgobat: Could this enhancement be implemented to all font sizes?

KUL is also interested for the 16 and 17pt (mainly for the Arial & Times New Roman font styles).

Kind regards,

Vangelis Palaskas.

**Comment by mgobat** [comment]
Available in v1.2.5. Please test and report back; no access to this font.

**Comment by VangelisPalaskas** [comment]
Sorry for the delay. I was able to test today the font size. 

The different font size works well @mgobat.

Thank you for the enhancement!
