### ISSUE TITLE
Receiving Department Items does not detect barcodes

### ISSUE THREAD

**Issue by kremke** [ExLibrisGroup/spineomatic-cloudapp#60]
Hi,

After receiving items and going to the “Acquisitions” -> “Receiving Department Items” page the newly received items are displayed, and this would be a logical place to print out the labels, but for some reason Spineomatic doesn’t pick the barcodes up; no green dot appears in the Cloud App icon and if Spineomatic is started up manually it doesn’t detect the barcodes (see attached screenshot). 
![2022-02-08_12h17_56](https://user-images.githubusercontent.com/76584888/153172866-deb8c1c3-d2b2-49f6-8f73-fbace7a402ed.png)

Regards,

Helgi Steindal

**Comment by mgobat** [comment]
The SpineOMatic Cloud App should be available from the specified Alma page in the 2022 April Alma release.
