### ISSUE TITLE
Parsing Routine for Dewey with long call numbers

### ISSUE THREAD

**Issue by MaggieMcGee** [ExLibrisGroup/spineomatic-cloudapp#61]
Hi Josh,

I wonder it the Parsing Routine 5 fix had an impact on other parsing routines. A library in SUNY using Dewey and has been using Parsing Routine 3 successfully with long call numbers. They just noticed that longer call numbers are not splitting properly any more.

Example of a call number: 
782.421649092 R134 2021

Label should look like:
782.42164
9092
R134
2021

Actually looks like now:
782.42164
R134
2021

The remaining numbers are being cut off: 9092

Thanks,
Maggie

**Comment by phoenixcomet** [comment]
I actually just checked our original documentation, and the DCC call numbers for the past few years have been parsing on the decimal point.

Example of a call number:
782.421649092 R134 2021

Label should look like:
782
.4216
 49092
R134
2021

Actually looks like now:
782.42164
R134
2021

The remaining numbers are being cut off: 9092 

So the call number is not breaking at the decimal point as it should and then it's not continuing the call number to the next lines.

Regards,
Tina Kiernan

**Comment by MaggieMcGee** [comment]
Hi Tina,

Thanks for the correct format. 

@jweisman I tested the following parsing parameters and the numbers are being cut off:

Parsing routine 1
782
.42164909
R134
2021

Parsing routine 2
782.42164
R134
2021

Parsing routine 4:
782
.42164909
R134
2021

Parsing routine 5
782.42164
R134
2021

Parsing routine 6
782
.42164909
R134
2021

Parsing routine 7
782
.42164909
R134
2021

Parsing routine 8
782
.42164909
R134
2021

Parsing routine 9, 10,  doesn't print anything

Parsing routine 11
782.42164
R134
2021

Parsing routine 12
782
.42164909
R134
2021


None of the parsing routine will allow for dewey call numbers with large classification numbers to be printed properly. As Tina mentioned above, the label should look like this:
782
.4216
49092
R134
2021

This is when the feature to edit the call number before printing would come in handy or create a parser that is designed for Dewey specifically and can handle long classification numbers.

Thanks,
Maggie

**Comment by MaggieMcGee** [comment]
HI @jweisman 

How can we get the labels to parse properly? None of the options work. 

Thanks,
Maggie

**Comment by mgobat** [comment]
Hi @MaggieMcGee. Reviewing our [knowledge base article](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/Physical_Resource_Management/070_Configuring_Resource_Management/060_Configuring_Call_Number_Parsing_when_Printing_Labels) on Call Number Parsing, it looks like routine 8 gets you closest to your needs. Would you agree that routine 8, with perhaps some enhancements when the number of digits after the decimal exceeds 7, might solve the problem?

**Comment by MaggieMcGee** [comment]
Hi @jweisman ,

The reality is, parsing parameter 8, parsing parameters 1,4,6,7,8, and 12 currently all print the same if you see my above examples. There is not change in behavior when selecting these parsing parameters. 

Thanks,
Maggie

**Comment by mgobat** [comment]
Hi @MaggieMcGee . Thanks for your reply. Let's take a look at the details of parsing routine 8:

- Split the call number at spaces, periods, and subfield i.
- If the character ^ is present in the call number, it is converted to a space but does not break at that point.
- If the number of digits after the period is more than 4, break as follows:
     - 5 = 3, 2
     - 6 = 3, 3
     - 7 = 4, 3

Your example, 782.421649092 R134 2021, has 9 digits after the decimal. Do you have any cases that would exceed 9 characters?  We could look at the option of adding a new parsing routine that handles more than 7 digits after the decimal. How would you expect 8 digits to split, 4 then 4? How about 9 digits, 4 then 5? Anything beyond 9 digits?

Thanks...

**Comment by MaggieMcGee** [comment]
Hi @mgobat 

I am attaching how it prints using call number parsing 3. It is not correct, but getting better. The label should look like this: 

782
.4216
49092
R134
202

![long_call_number_parser](https://user-images.githubusercontent.com/81188041/157085315-73cdf616-6c46-4101-beb0-b96cdb90bfbb.jpg)
1

**Comment by mgobat** [comment]
Thanks for the feedback, @MaggieMcGee. I updated the parser to split first at 4 digits (with decimal), then subsequently split every 5 digits. Please give it a try.

**Comment by MaggieMcGee** [comment]
@mgobat 

The label printed as expected this time. I am asking for more barcodes with varying length call numbers to test to make sure they print as expected.

Thanks,
Maggie

**Comment by mgobat** [comment]
Hi @MaggieMcGee...
Any additional feedback on the "long dewey" parser?
Thanks.

**Comment by MaggieMcGee** [comment]
@mgobat 

It seems to be working as expected  now. One request to be able to  indent the rows with the rollover Dewey number by a space or two? 

Thanks,
Maggie
