### ISSUE TITLE
no label appears on screen

### ISSUE THREAD

**Issue by pmgator** [ExLibrisGroup/spineomatic-cloudapp#64]
In trying to print spine labels, nothing appears on the screen.   Scan the barcode click to print label and the label looks blank on the computer screen.  Thanks for any feedback.

**Comment by mgobat** [comment]
@pmgator, could you please provide the details of the template and layout you are using? Thanks.

**Comment by pmgator** [comment]
The layout is "Label Printer Roll" and the template is "Call Number Label Book"  I am not very good with technology and generally just click to print.  But two other people also had trouble.  This is code for "I don't want to make it worse."

**Comment by mgobat** [comment]
@pmgator, could you ask whoever created the "Label Printer Roll" layout and the "Call Number Label Book" template to give you the details of how the layout and template are defined? Thanks.

**Comment by pmgator** [comment]
I will, thank you.

**Comment by DundeeKarin** [comment]
Also having the same problem

**Comment by mgobat** [comment]
@DundeeKarin, can you please provide the contents of both the layout and template that you are using?

**Comment by DundeeKarin** [comment]
Good Morning

I have attached a screencast detailing your requirements.

We currently use the local SpineOMatic setup, installed on a pc in our processing department - making it available via the Alma cloud would be much more beneficial.

Here is a screenshot of how the label prints from there and how we would want it to print from the cloud.

[cid:c875f3bf-0b5b-4d4a-a76b-77c4ed68e0d6]

We currently use a Brother p-touch printer to print out the labels.

Thanks.
Karin

[University of Dundee shield logo]<http://uod.ac.uk/sig-home>
Karin Culley  (Working days: Wed - Fri)
Digital Library Services | Research & Resources
Library & Learning Centre | Main Library
University of Dundee | DD1 4HN
+44(0)1382 384097 | ***@***.******@***.***>

________________________________

**Comment by DundeeKarin** [comment]
As requested screenshot/cast sent directly 21/4

**Comment by mgobat** [comment]
@DundeeKarin, are the labels really only .3 centimeter wide and .24 centimeter high? That's a very tiny label to print on. Also, it appears you don't have a "Page width" set nor a number for the "Labels per page". I had the same results as you with the same settings, but once I set the label height and width to something larger (3cm and 2.4cm), and set values for the "Page width" and "Labels per page", the labels appeared correctly.

**Comment by mgobat** [comment]
@DundeeKarin, can you provide a screenshot of the "Print Setup" tab in the SpineOMatic Windows application that prints successfully for you?  Thank you.

**Comment by mgobat** [comment]
Closing due to lack of response.
