### ISSUE TITLE
Question: How to increase space between Alma fields that exist within a table

### ISSUE THREAD

**Issue by VangelisPalaskas** [ExLibrisGroup/spineomatic-cloudapp#65]
Dear Ex Libris team,

I have a rather silly question. I want to display two Alma fields (Parsed Call Number & Barcode) next to each other on my label. To align them harmoniously I use a table with 'invisible' borders. However, I would like to increase the gap between them and it is hard for me to find a way. Please see screenshots below.

Q: Is there a way to increase/adjust the gap between two table cells? 

![image](https://user-images.githubusercontent.com/89778038/162378504-6e9d3f78-156b-400c-b7fe-8abce43c7bcf.png)

I am looking forward to your answer.

Kind regards,

Vangelis Palaskas.

**Comment by VangelisPalaskas** [comment]
FYI

I have solved the case by adding empty table cells in-between. But just out of curiosity: 
Is there a better/alternative way that you would recommend maybe through the table properties?

Kind regards,

Vangelis Palaskas.

**Comment by mgobat** [comment]
@VangelisPalaskas, the way you solved it is our recommendation. There is a "cell padding" property on the table that adds padding, but it does so all around the cell content. That would probably cause your labels to not align/print correctly.

**Comment by VangelisPalaskas** [comment]
@mgobat Thank you very much for the response.

Kind regards,

Vangelis Palaskas
