### ISSUE TITLE
Zebra spine label printer with "Generic/text only" driver incompatible with SpineOMatic cloud app

### ISSUE THREAD

**Issue by HSteeleLTS** [ExLibrisGroup/spineomatic-cloudapp#66]
Good morning,   

You had responded to me some ago about trying configuration settings in another ticket to handle spine and pocket labels in the template.   I see that you had us define three columns, where one is the gutter between the two.  Thanks for pointing me to these configurations.

The problem is the printer, still doesn't respect these two separate parts of the label.  The issue I believe is that our printer setup with Zebra requires that we send a generic/text only job to the printer, whereas as the label the SpineOMatic printer is sending appears to be a web request, with html table information.  Also the URL is actually being printed to the label.  The reason we have this kind of driver is because with the way our printer is set up, all of the formatting, font etc is part of the printer configurations itself and saved on the printer.  So it requires generic/text only input.  This works with the SpineOMatic standalone app, but I haven't gotten this to work with the cloud app.

Do you have any ideas about how we could get the cloud app to work given our environment?  The cloud app obviously has lots of advantages and we would love to use it.

**Comment by mgobat** [comment]
@HSteeleLTS, which printer do you have and what label stock are you using? Thanks.

**Comment by HSteeleLTS** [comment]
We're using a Zebra printer.  It's somewhat old.  I think ZM400 maybe.  And the stock is total 4.25" wide  thermally printed labels including margins, that I believe roughly correspond to the dimensions you laid out in the other ticket.

the spine label is 2 cm x 3.5cm.  and the pocket label is 7.3 cm x 3.5 cm

**Comment by mgobat** [comment]
@HSteeleLTS, your printer is a significant challenge since the SpineOMatic Cloud App is browser-based and therefore designed to output HTML. Adding support for printers like yours may not be possible in the app's current design.

**Comment by mgobat** [comment]
@HSteeleLTS, I've created an enhancement request (#70) for this issue. We can track against that issue if other customers also are using printers requiring generic/text only.
