### ISSUE TITLE
Request to add ALA BT Courier Font

### ISSUE THREAD

**Issue by mar1ll10n** [ExLibrisGroup/spineomatic-cloudapp#67]
I would just generally like to use the other fonts installed on the computer. The ALA BT Courier font is installed on our staff PCs, but I am not sure why they are not accessible in the SpineOmatic CloudApp. We are use it with the SpineOmatic stand-alone program.

Thanks.

**Comment by mgobat** [comment]
Available in v1.2.5. Please test and report back; no access to this font.

**Comment by mgobat** [comment]
No feedback; closing assuming it is fine.
