### ISSUE TITLE
Add configurable padding before label

### ISSUE THREAD

**Issue by YoelKortick** [ExLibrisGroup/spineomatic-cloudapp#7]
When a call number is left justified it prints all the way at the edge of the label 
See attached file for details
[When a call number is left justified it prints all the way at the edge of the label .docx](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6189892/When.a.call.number.is.left.justified.it.prints.all.the.way.at.the.edge.of.the.label.docx)

**Comment by mck1777** [comment]
I am having this issue as well.
[labelTest.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6192354/labelTest.pdf)

**Comment by jweisman** [comment]
I hope it's enough to add a 0.05in margin. Would rather not make it configurable unless absolutely necessary.

![Screen Shot 2021-03-25 at 13 24 12 ](https://user-images.githubusercontent.com/80420/112465519-7e9b7100-8d6d-11eb-9901-3de729011133.png)

**Comment by MaggieMcGee** [comment]
Hi Josh,

I think libraries will want to choose left-justify margins. The left side if the label often-times wraps on the side of the book spine, so there needs to be enough space to allow that. For example, one left-justifies .2

Thank you for investigating this,
Maggie

**Comment by jweisman** [comment]
We're now supporting a configurable padding before the label text. Hope that resolves this issue.
