### ISSUE TITLE
Call no no longer parsed correctly

### ISSUE THREAD

**Issue by kremke** [ExLibrisGroup/spineomatic-cloudapp#74]
Hi,

We went live with Alma last Monday, and now I am getting complaints from the libraries that the Call no is not parsed correctly. I have checked, re-checked and triple checked that there is indeed a check marck in Line breaks between call number parts

![image](https://user-images.githubusercontent.com/76584888/173803538-3016be8e-814f-4ac0-b0ca-e34e942d7ab3.png)

When we did our testing and setting up before going live, the call nos were split by space, but now this has stopped working? (see screenshots of before and now below).  Can you help us out?
![before](https://user-images.githubusercontent.com/76584888/173803829-430cd02e-7a9f-4b4f-a18e-db63607b9cb3.jpg)
![now](https://user-images.githubusercontent.com/76584888/173803834-7c611853-1dc5-4a01-a2ed-09779696cbbe.jpg)

Here are the fields I'm using.
<html>
<body>

{{field:holding_data.call_number}} |  
-- | --
{{field:item_data.library.desc}}{{field:item_data.barcode}}
{{field:raw_barcode}}{{field:bib_data.author}}{{field:bib_data.title}}{{field:holding_data.call_number}}{{field:item_data.library.desc}}

<p style="font-size: 14px; font-weight: 300; color: rgb(94, 94, 94);"><br style="color: rgb(94, 94, 94); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Open Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 300; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</body>
</html>

Regards,

Helgi Steindal

**Comment by mgobat** [comment]
@kremke, looks like you are using the "Default (Alma)" parser in your templates. That parser hasn't changed. We added a new parser, "Item Call Number Split By Slash", but that shouldn't affect anything if it isn't being used in your template. And I don't see any changes in the code for the line breaks checkbox.

**Comment by kremke** [comment]
Hi Mark,

I figured it out, it seems that there is a new parsing routine, Long Dewey, that splits the call no correctly.  Some time ago you fixed the barcode for us, adding a new field raw_barcode to display the barcodes as digits on the pocket label.  Could you do the same for the call no, it needs to go on the pocket label as well, but as far as I can see, there is currently no way of getting a parsed call no on the spine label while having it in one line on the pocket label.  Now that all the libraries have started using SpineOmatic for their new items, we are finding that when the call no. on the pocket label is being split up into many lines, other data will not fit on the label.

Could you please look into the possibility of creating a raw_call_no field where the data is not parsed?

Regards,

Helgi Steindal

**Comment by mgobat** [comment]
@kremke, so if we added a new call number field that ignored the setting for "Line breaks between call number parts", but otherwise behaved like the other call number fields, would that solve the problem? If so, what name would make sense for that field? "Raw call number" or something else?

**Comment by kremke** [comment]
Hi @mgobat ,

Yes, having the whole call no in a field that would print as a single line would do the trick. I guess it doesn't matter all that much what the field is called so long as it works, but calling it Raw call no makes sense since it is analogous to the raw barcode field.

Now that we are live with Alma I've got 300 libraries asking for help setting up their label printers and asking for all kinds of tweaks so this is quite a daunting task.  Having the ability to print the call no string in one line will help me a lot.

Regards,

Helgi

**Comment by sthb13** [comment]
Hi Mark,

Helgi and I have been trying to set up the labels in spinomatic according to the libraries' wishes. Before I used the default Alma parsing routine and then the call numbers were split on spaces. Then that stopped working so the Long Dewey routine was used instead. Now the libraries are complaining that the Call number is being split on a dot as well. Can you point us to a routine that only splits the call number string on spaces? If there is no routine that splits on spaces only, would it be possible to add such a routine?

Regards, Skuli

**Comment by mgobat** [comment]
@kremke, since the original topic of this issue is no longer a problem, I'm going to close it and open a new issue for the "raw call number" enhancement.

**Comment by mgobat** [comment]
@sthb13, I'm going to close this issue and open an enhancement request for a call number parser that only splits on spaces.
