### ISSUE TITLE
Spineomatic won't open in Alma

### ISSUE THREAD

**Issue by YvonneKester** [ExLibrisGroup/spineomatic-cloudapp#75]
Hello,

Just a heads up that the app won't open--I thought it might be because you were working on the call number parsing issue, but in case you weren't aware....

Thanks!
Yvonne

**Comment by mgobat** [comment]
Thanks, @YvonneKester, We had an issue with some Cloud Apps which should be resolved now.

**Comment by YvonneKester** [comment]
@mgobat Brilliant! Thanks!
