### ISSUE TITLE
Enhancement: Print two templates with one layout

### ISSUE THREAD

**Issue by VangelisPalaskas** [ExLibrisGroup/spineomatic-cloudapp#77]
Hi @mgobat,

I have been asked from many libraries in our network ([LIBISNet](https://libis.be/libisnet-partners)) if it can become possible to print two different labels at the same time. This feature exists in our old label printing tool. However, we have managed to convert already many institutions to the SpineOMatic cloud app. 

Would it be possible to print two different templates (e.g. Spine & Barcode) simultaneously?

![image](https://user-images.githubusercontent.com/89778038/175243778-bad34b7f-b9df-4514-bfb0-0c0c40825258.png)

![image](https://user-images.githubusercontent.com/89778038/175245404-ef38aa37-44ce-45f7-ab3a-a52ce863b673.png)

Kind regards,

Vangelis Palaskas.

**Comment by mgobat** [comment]
@VangelisPalaskas, we've made a first attempt at supporting more than one label per layout by implementing tables in the layout.  Please see https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#printing-adjoining-labels. The assumption is that you would be printing multiple labels next to each other, but you may be able to adjust it for your needs. Let us know if that might work for you. Thanks.

**Comment by VangelisPalaskas** [comment]
Thank you for the answer @mgobat.

In fact didn't think of this yet. So it's a nice idea. 

I will give it a try and come back to you.

**Comment by VangelisPalaskas** [comment]
Hi @mgobat,

I have performed some tests and it looks that your idea works! This is how the spine & barcode label get printed together (one template & layout):
![image](https://user-images.githubusercontent.com/89778038/177161334-491de5d1-9ba5-449d-9471-ff93ea04db2f.png)

*The only disadvantage is that I cannot control well the top margin of the second label (top label is second). I choose this sequence because in the Barcode, the Call Number is standardised (1 line) whereas in the spine label the Call Number might have 1, 3 or 4 lines.

There is an issue though when I try to print many labels together:
![image](https://user-images.githubusercontent.com/89778038/177161584-b5e8de3d-01f5-4ee6-abdc-5bdbb24a7114.png)

I understand that this happens because we use one layout with extended label height to fit two templates. 
The difference is that in the proposed solution the cloud app should print each template separately by using the same layout settings. That way it should manage to print double labels for items in bulk. I had this question from my colleagues in the library because they wanted this option. 

Conclusion: I am already happy that your idea works but if there would be a case that you would consider my initial idea please let me know 🙂.

**Comment by mgobat** [comment]
@VangelisPalaskas, glad the tables in templates helps with your situation. And yes, we'll leave your original issue as an enhancement request to be considered in a future release.

**Comment by VangelisPalaskas** [comment]
Perfect! 

Thank you very much 💯 .

**Comment by mgobat** [comment]
@DiederikL, thank you for this update. Glad things are working better for you. 

I'm going to close this issue since it has deviated from the original enhancement request from Vangelis. If you feel that Vangelis' original enhancement request would benefit your institution, please open a new GitHub issue.

Thank you!
