### ISSUE TITLE
Enhancement request: Add TinyMCE tools to the editor.

### ISSUE THREAD

**Issue by kremke** [ExLibrisGroup/spineomatic-cloudapp#79]
Hi @mgobat ,

Our CS guy found out that the editor that spineomatic uses has a feature that allows the html code to be manipulated, he asked me to post an enhancement request:

We (ILC consortium) have an urgent request that would help us a lot with our workload at the moment. The SpineOMatic cloud app is using the TinyMCE editor and it has a feature or option under 'Tools' -> 'Source Code' that is currently not activated in the cloud app. This feature is not part of the premium features so including it in the cloud app shouldn't be a problem. Could you activate this feature for us, it would help us a lot as we have to customize labels for hundreds of libraries and could do that on a more precise text basis with less time consuming and error prone editing in the GUI.

Thank a lot and best regards

Helgi Steindal

**Comment by mgobat** [comment]
Available in v1.2.7.
