### ISSUE TITLE
If the call number does not have a subfield k then it prints higher than call numbers which do have a subfield k

### ISSUE THREAD

**Issue by YoelKortick** [ExLibrisGroup/spineomatic-cloudapp#8]
If the call number does not have a subfield k then it prints higher than call numbers which do have a subfield k
See attached file for details
[If the call number does not have a subfield k then it prints higher than call numbers which do have a subfield k.docx](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/6189893/If.the.call.number.does.not.have.a.subfield.k.then.it.prints.higher.than.call.numbers.which.do.have.a.subfield.k.docx)

**Comment by jweisman** [comment]
The API returns an extra parsed line for the barcodes with a `$$k`:

**AU65657**:
```javascript
"call_no": ["", "CD", "704", "S559", "2000"]
```
**AU65667**:
```javascript
"call_no": ["", "Ref.", "020.56", "B786", "2020"]
```

We'll have to investigate the API.

**Comment by jweisman** [comment]
In the meanwhile we're now suppressing blank lines in parsed call numbers. Hope that will address this issue.

**Comment by YoelKortick** [comment]
It does look good now, all labels start in same place regardless of whether they do or do not have a subfield k in the 852 field

***@***.***D724AC.48D9D810]
