### ISSUE TITLE
Paging not working correctly

### ISSUE THREAD

**Issue by sthb13** [ExLibrisGroup/spineomatic-cloudapp#81]
Hi Mark, first thank you for the quick update yesterday. It's a tremendous help to be able to edit the source code of the layout itself. However I discovered today, that the Label per Page setting isn't working correctly. The first page looks correct, but all the following labels spread out on the following pages without page breaks.
Example:
I have 19 items selected
![2022-06-28_12h46_36](https://user-images.githubusercontent.com/42750168/176184084-5b76f2fe-0b2a-45b9-ae72-262488e2f57c.png)
When I open the print dialog the first page looks correct (assuming I want to print to PDF, so it isn't a printer driver issue)
![2022-06-28_12h52_33](https://user-images.githubusercontent.com/42750168/176184291-076cad62-98eb-45e7-a712-ef736ad2cabd.png)
But the following labels should be printed on 18 separate pages, but are spread on 6 pages.
![2022-06-28_12h53_01](https://user-images.githubusercontent.com/42750168/176184551-e9d2abdf-c3d6-486b-ac88-bff623c22714.png)
This behavior has been confusing us and we had all kinds of offset issues, but I just hadn't noticed that the paging isn't working at all, as the page size and the label size were mostly identical.
It would also be very helpful to have real margin less printing as an option somewhere. Now there is always the default 8px (about 2mm) margin from the html body tag on all sides of the page which complicates calculations on small pages with multiple labels and fields with little tolerance.

Thank you and best regards,
Skuli, Icelandic Libraries Consortium (ILC)

**Comment by mgobat** [comment]
@sthb13, since you just noticed this, you can't confirm this was happening pre-1.2.7, can you? None of the changes in v1.2.7 should be affecting paging...

**Comment by mgobat** [comment]
@sthb13, thanks. I'm glad it isn't new.

**Comment by mgobat** [comment]
@sthb13, could you please provide the details of your template and layout? Thank you.

**Comment by mgobat** [comment]
@sthb13, I think the problem may be the "Top margin" setting in the layout. Is yours zero by any chance? If so, what happens if you change it to .1?

**Comment by mgobat** [comment]
Included in release v.1.2.9.
