### ISSUE TITLE
Margins in Print

### ISSUE THREAD

**Issue by sthb13** [ExLibrisGroup/spineomatic-cloudapp#82]
Hi Mark,

Sorry to bother you again, but we are in troubles fulfilling the printing demands of our biggest library institution (all public libraries in Iceland). Please have a look at the example below. The left label is how they were produced in the old system, now with SpineOmatic the right label is as close as I can replicate it. 

![20220629_124856](https://user-images.githubusercontent.com/42750168/176444312-1a3ebcbd-a9d0-4a40-98d5-82ad554db149.jpg)
The **main** problem is the 8px pixel margin surrounding the whole page as you can see on screenshot below that I made on our sandbox and tweaked SpineOMatic to show the html document.
![2022-06-29_13h56_36](https://user-images.githubusercontent.com/42750168/176455190-853998a8-ea46-4552-a425-4ec1c75f58e7.png)

Then there is **another** padding above the the table of 0.5in(?).
![2022-06-29_13h07_52](https://user-images.githubusercontent.com/42750168/176445871-4176fb3f-7782-4dba-9267-7cbbafd8315a.png)
![2022-06-29_13h21_43](https://user-images.githubusercontent.com/42750168/176447571-d7abd641-a3ec-43d7-9c12-814b6aced8d3.png)

An **additional** problem is the margin around the barcode itself, there is considerable whitespace surrounding it, making it very hard to use on small labels (our is just 1.5cm in height).
![2022-06-29_13h28_45](https://user-images.githubusercontent.com/42750168/176448557-bcfb25df-a7bf-41a3-be5a-3ecbadeaaa69.png)

At least the first 2 issues would be easy to fix to get a similar result like in the screenshot below.
![2022-06-29_13h39_43](https://user-images.githubusercontent.com/42750168/176450990-605e3507-3a11-4fcb-9c31-229f01ca5dca.png)
I think it would be easiest to add a checkmark next to "Print gridlines" to print without default margins and paddings.

Hope you understand our problems and thanks for your efforts
Skuli (ILC)

**Comment by mgobat** [comment]
Included in release v.1.2.9.
