### ISSUE TITLE
Font setting not retained

### ISSUE THREAD

**Issue by rolson57** [ExLibrisGroup/spineomatic-cloudapp#83]
No matter what I select as the font in our template, it always reverts back to System Font 10pt. Yes, I do click "save" each time. What could I be missing?

Thanks,
Roger Olson
San Diego Community College Distrct
![Capture](https://user-images.githubusercontent.com/108420854/176486745-6f003f95-9429-4325-ab1c-8f09f1d95226.PNG)

**Comment by mgobat** [comment]
@rolson57, when creating a new template, or returning to edit an existing template, the font will default back to the system font. The "Save" only saves the contents of the template, not any settings in the template editor. 

Or are you saying that contents in a saved template previously set to another font is being reset to the system font?

Thanks.

**Comment by rolson57** [comment]
What I was seeing was that, when another user at our institution opened the SpineOMatic app on her computer and printed labels, the font was too small. So I went back to the template editor and saw it showing 10pt (I had set it to 14pt), so I assumed that the template had regressed back to 10pt.  If I set the font to 14pt in the template editor, it should be 14pt for all users at our institution who use that template, right?

Thank you.

**Comment by mgobat** [comment]
@rolson57, yes, the template should use the font and font size originally set, unless the user's workstation doesn't have the selected font installed.

**Comment by rolson57** [comment]
As an experiment, I printed out three batches of labels on my own workstation. I set a different font and font size in the template editor before printing each batch: Arial 10pt for the first, Courier New 14pt for the second, and Times New Roman 8pt for the third. The three batches of printouts were identical.  Changing the font and font size in the template didn't change anything.

**Comment by mgobat** [comment]
@rolson57, what printer are you using? Thanks.

**Comment by rolson57** [comment]
HP LaserJet 600 M602

**Comment by mgobat** [comment]
Thanks, @rolson57. Not the answer for which I was hoping. I suspect there could be many problems with specialized label printers (since the SpineOMatic Cloud App's output is HTML), but didn't expect it to be a LaserJet.  That is puzzling.

**Comment by sthb13** [comment]
I was experiencing similar problems. The GUI editor is adding <span> elements with font rendering instructions, often overriding and adding more and more rules, depending on how you select the element. I am not quite sure what logic is at work here, but after inspecting some of the templates there were lots of weird (and contradicting) font rendering instructions in the code. The only sane workaround is the source code button, where you can inspect what it is actually going to output and clean it up there.

**Comment by rolson57** [comment]
Thanks, @sthb13. This is what my source code looks like, regardless of what font or font size has been selected:

<p style="text-align: left;"><span style="font-size: 10pt;">{{field:prefix}} </span><span style="font-size: 10pt;">{{field:item_data.call_no}}</span></p>
<p style="text-align: left;"><span style="font-size: 10pt;">{{field:item_data.description}}</span></p>
![Capture](https://user-images.githubusercontent.com/108420854/177353083-58da1234-a2bd-4634-8693-690807c41e4c.PNG)

**Comment by mgobat** [comment]
@rolson57, what happens if you select text in the template, then select the Webdings or Wingdings font from the font dropdown? Does the text change to the symbols?

System Font:
![system font](https://user-images.githubusercontent.com/45852490/177366475-45a656e7-8e20-452e-a73e-432efa0b4ebd.png)

System Font and Webdings Font:
![webdings](https://user-images.githubusercontent.com/45852490/177366540-80add9f0-9a5a-4664-a543-c6d364f30ee5.png)

**Comment by rolson57** [comment]
This is what happened when I changed the font to Wingdings, 12pt
![Capture](https://user-images.githubusercontent.com/108420854/177370608-a078d968-eda5-4a3b-83cc-cd8cfe0d4913.PNG)
![Capture2](https://user-images.githubusercontent.com/108420854/177370730-6d63833e-ac77-455e-ba1d-6c23d1805aa6.PNG)

**Comment by mgobat** [comment]
@rolson57, and does it print the Wingdings? It looks like the font selection is working ("font-family: wingdings" in the source). If you select the same text and pick another font, then look at the source, it doesn't change the "font-family" to the font you selected? Thanks.

**Comment by rolson57** [comment]
Yes, the Wingdings did print.  I think my solution is to edit the source code directly (exactly what @sthb13 suggested).
Thank you very much!
