### ISSUE TITLE
Question: Top Margin in Multiple labels

### ISSUE THREAD

**Issue by VangelisPalaskas** [ExLibrisGroup/spineomatic-cloudapp#84]
Hi @mgobat,

We have noticed that when someone prints multiple labels an extra 0.1cm is added to the Top Margin only of the first label:

![image](https://user-images.githubusercontent.com/89778038/177164915-5eaaef3c-f068-436d-93eb-6cf0a36b01fb.png)

We have set no Top Margin in the windows printing preferences.

Is it possible that this is a small bug and that it will be fixed in the next version?

Kind regards,

Vangelis.

**Comment by kremke** [comment]
I think this might be the same problem as described in issue #81 It seems that when printing multiple labels Spineomatic puts the first label on a seperate page but the rest are put on one page and the placing of the labels gets messed up because it is not accounting for the label gap.

Regards,

Helgi

**Comment by mgobat** [comment]
@VangelisPalaskas, what is your "Top margin" set to in the "Layout" you are using? I believe we have a paging issue if the "Top margin" is less than 0.001 (inches or cm). Looking at your sample, I think you probably don't have a "Top margin" below 0.001...and it doesn't appear to be a paging issue as your labels look to all be on the same page or on a continuous roll. Is that correct? Thanks.

**Comment by jonahhighmanUWA** [comment]
Hi @mgobat, I'm having this same problem. I did lots of trial and error getting it to fit on our spine labels, then when tried printing mulitples at once and the second and subsequent pages all had a slightly shorter top margin. These are on a continuous roll, but each label is treated as a separate 'page' both in my SpineOMatic settings and by the label printer driver.

![SUNIT-PTR-022101910410 (002)](https://user-images.githubusercontent.com/113404105/196582631-1495e754-cef7-4444-ac3a-b5b2d6e5e6b7.jpg)

**Comment by mgobat** [comment]
Included in release v.1.2.9.
