### ISSUE TITLE
Printing call no. with and without prefix in one go

### ISSUE THREAD

**Issue by KatieLai** [ExLibrisGroup/spineomatic-cloudapp#87]
Hi, I have created a template that includes different prefixes.  I was hoping to use it to print call numbers with and without a prefix.  However, it seems that those without a prefix will have an extra line inserted before the class no., making the first line of the text drop lower than normal.  Is there a way to remove the extra line when there is no prefix?

I suppose I can create separate templates, one for with prefix and one for without, but it would be much more efficient if we can just close our eyes, scan all the barcodes, and print everything in one go.

<img width="500" alt="Screenshot 2022-08-03 at 5 02 46 PM" src="https://user-images.githubusercontent.com/110567414/182712075-5ba2b957-42a9-46d2-a6c0-977f76debe04.png">

Thanks in advance for your advice.

PS: Using Parting routine 5, Verdana 12

Katie

**Comment by mgobat** [comment]
@KatieLai, could you provide the details of the template you are using? Thanks.

**Comment by KatieLai** [comment]
Hi @mgobat 

Here are the details of my tempate "Print Book with Prefix."

<img width="292" alt="Screenshot 2022-08-04 at 12 15 21 PM" src="https://user-images.githubusercontent.com/110567414/182897989-b625e2f4-dca9-4130-8e81-949fcc54c117.png">
<img width="278" alt="Screenshot 2022-08-04 at 12 15 28 PM" src="https://user-images.githubusercontent.com/110567414/182898088-7b4ce84f-0c23-4e0e-be6b-5641c78a4ca3.png">
<img width="244" alt="Screenshot 2022-08-04 at 12 15 49 PM" src="https://user-images.githubusercontent.com/110567414/182898149-568b1a93-688b-4937-8d4b-1eda9fd21f8c.png">
<img width="211" alt="Screenshot 2022-08-04 at 12 15 58 PM" src="https://user-images.githubusercontent.com/110567414/182898188-26e93d86-3aab-4184-ba6c-2893a3a59d39.png">

Here is my layout
<img width="1111" alt="Screenshot 2022-08-04 at 12 18 29 PM" src="https://user-images.githubusercontent.com/110567414/182898969-240aa1e1-2c3a-4e08-bf6b-a4980c6b866c.png">

Btw, may I know what "left padding" means?

Thanks again for your help.

Katie

**Comment by mgobat** [comment]
@KatieLai, thank you for the template details. I will take a look.

Left padding refers to an indentation in the label before the text starts. Here's an image of where/how the settings apply:
![somlayout](https://user-images.githubusercontent.com/45852490/182929611-a6547243-0343-47e6-8f46-7b8d147464ce.png)

**Comment by mgobat** [comment]
@KatieLai, unfortunately suppressing the blank line when there is no prefix to print cannot be done with the way the SpineOMatic Cloud App is designed.  We could change this to enhancement request, but unless there are more users that need this functionality, it is unlikely to be added.
