### ISSUE TITLE
Add ability to toggle line breaks for description and/or all fields like call number parts

### ISSUE THREAD

**Issue by fesnakm** [ExLibrisGroup/spineomatic-cloudapp#91]
Would be helpful to have the description on separate lines like the call number is, specific to serial publications. if possible, it would also be useful to be able to toggle all spaces onto new lines 

![description field spineomatic](https://user-images.githubusercontent.com/114007192/191298180-639700f2-e45d-4ba9-9a12-af39b916460d.jpg)

**Comment by mgobat** [comment]
@fesnakm , @BarbaraSalfate, @reedkay...just to clarify; this configuration option would be for the item_data.description (issue level description) field when included in a template?

**Comment by mgobat** [comment]
Available for item_data.description field in release v1.3.1.
