### ISSUE TITLE
documentation on "suppress copy numbers"

### ISSUE THREAD

**Issue by arschlegel** [ExLibrisGroup/spineomatic-cloudapp#93]
While I believe it can be used simply to choose NOT to display a certain number, like 1, I cannot seem to find any documentation about the copy numbers options, and would greatly appreciate it! 

=================================================
My curiosity stems from the fact that I cannot get prefixes OR suffixes to print correctly today, which is another matter entirely. But I think this documentation enhancement would be welcome. 

Thank you for ALL of the amazing work you do on this app; I know many rely on it and it requires a ton of customization.

**Comment by mgobat** [comment]
@arschlegel, your understanding is correct. The documentation is updated. Please open a new issue if you discover it is not working for you. Thank you.
