### ISSUE TITLE
Use individual parsed call number lines, or limit the number of lines displayed from the parsed call number

### ISSUE THREAD

**Issue by jonahhighmanUWA** [ExLibrisGroup/spineomatic-cloudapp#94]
Hi there,

Our spine labels fit up to 8 lines of text. In our current desktop implementation of SpineOMatic, we use the 'Custom' call number format setting to directly arrange data from the XML sources:
```
<library_code>
<location_code>
<parsed_call_number><call_no_1>
<parsed_call_number><call_no_2>
<parsed_call_number><call_no_3>
<parsed_call_number><call_no_4>
<parsed_call_number><call_no_5>
<issue_level_description>
```
This lets us:
- exclude the 6th parsed call number line provided by Alma. The vast majority of our call numbers don't go into the 6th line, and it allows the issue level description to take precedence in the rare case that it does
- pull the library code direct to the label without setting up label prefixes on everyone's machines.

In testing the cloud app, I've been able to mostly replicate this with these field codes, and setting up label prefixes for each library code (works well as in the cloud app I only have to do it once for the whole institution)
```
{{field:prefix}}
{{field:item_data.location.value}}
{{field:item_data.call_no}}
{{field:item_data.description}}
```
My only trouble is that when 'item_data.call_no' goes into its full 6 lines, it pushes the label content past 8 lines and off the edge into the next label. This throws out the layout of the subsequent labels.

In template configuration, I either need:
- an option under the 'Call number' drop down to limit the number of lines that are displayed from the `{{field:item_data.call_no}}` parsed call number field
- the ability to insert individual call number lines as fields (e.g. `{{field:item_data.call_no_line_1}}`, `{{field:item_data.call_no_line_2}}` etc)

**Comment by mgobat** [comment]
@jonahhighmanUWA, would the problem be solved if we added an option labeled "Maximum call number parts", applicable only if the "Line breaks between call number parts" option is enabled? 

For example, if the call number was "Z56 .S69 1942", and the "Line breaks between call number parts" was checked, and 2 was specified as the "Maximum call number parts", what would get printed is:

Z56
.S69

**Comment by jonahhighmanUWA** [comment]
Hi @mgobat, Yes I believe it would - I would set the 'Maximum call number parts' option to '5' so that no more than 5 call number lines appeared on the label, so that (for example) 'QC 300 G662(9.03) F749(.03) +2' would result on the label:
```
QC
300
G662
(9.03)
F749
```

**Comment by mgobat** [comment]
Included in release v.1.2.9.
