### ISSUE TITLE
Demco 1-1/2" x 7/8"

### ISSUE THREAD

**Issue by YvonneKester** [ExLibrisGroup/spineomatic-cloudapp#97]
Hi,

I'm trying to tweak this layout/template in Alma--it isn't lining up correctly, but it doesn't have a table attached to it. Should it? Printout is migrating left. The screenshot had an offset applied, and she tries to show where the outlines of the lables are. I have played around with the layout a little, and tried putting in a one-cell table in the template, but nothing has worked. 

Thanks!
Yvonne
![SpineO](https://user-images.githubusercontent.com/105752712/204421057-34e51c95-5fa8-40b4-a22d-0d773ca29a89.JPG)

**Comment by YvonneKester** [comment]
Hello,
I visited the campus having issues, to see if I could figure out how to configure this, but nothing I tried worked. I tried a fresh "Demco Spine 1 1/2 X 7/8" Layout, and applied a one-cell table to that in the template. That did seem to help a little, but we are still far from printing usable labels. I'm attaching a photo of one of the printouts. The black outline is what prints out for gridlines, and the red is the actual outline of the labels. The first label prints nearly perfect, but as you look to the right, each label gets a bit more off, moving toward the left rather than keeping with the labels. Similarly, the top row is fairly correct, but each subsequent row migrates upward, until the bottom row prints on both of the two last rows of labels.

This campus is not able to print labels at all right now. Can you help? Please let me know if I can supply more information.

Thanks!
Yvonne
![IMG_20221130_111947105](https://user-images.githubusercontent.com/105752712/204895230-9a6c78c7-40f0-4308-836b-b6e7794550ce.jpg)

**Comment by mgobat** [comment]
Hi @YvonneKester.  Could you please add a comment here containing the settings from your selected layout, as well as the HTML of the selected template? You can get the template HTML by clicking the "<>" icon in the template editing toolbar. Thank you.

**Comment by YvonneKester** [comment]
Hi @mgobat ,

**Layout (in inches):**
Top margin: 0.6875 
Left margin: 0.3125
Page width: 8.5

Portrait orientation

Label width: 0.875
Label height: 1.5
Horizontal gap: 0.125
Vertical gap: 0.125
Labels per page: 48
Left padding : 0.05

**HTML from template:**
<table style="border-collapse: collapse; width: 100%; height: 100%; float: left;" border="1" cellspacing=".13" cellpadding="1">
<tbody>
<tr style="text-align: left;">
<td style="width: 100%; height: 100%; text-align: left; vertical-align: middle;"><strong style="font-family: 'arial narrow', sans-serif;">{{field:item_data.call_no}}</strong></td>
</tr>
</tbody>
</table>

And HTML template without a table:

<p style="text-align: left; vertical-align: middle;"><span style="font-family: 'arial narrow', sans-serif;"><strong>{{field:item_data.call_no}}</strong></span></p>


They started out using Long Dewey for the call number, and I changed it to Default (Alma) in order to allow for prefixes. I changed it back to Long Dewey, and that helped somewhat to get things back on track, but I'd like them to be able to use Default Alma with Arial Narrow font. 

Looking at the actual printout, the left margin is 6/16" and the right margin is 10/16". The top margin is 13/16" and the bottom margin is 1 and 3/16". 

Thanks!

**Comment by YvonneKester** [comment]
``
[SpineOMatic HTML.txt](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/10156468/SpineOMatic.HTML.txt)

**Comment by mgobat** [comment]
Thanks for the details, @YvonneKester. We will take a look. Have you tried the new "Enable marginless templates and layouts" option to see if it helps? It was an addition from the Consortium of Icelandic Libraries for printing on small labels.

**Comment by YvonneKester** [comment]
Thanks! 
She tried the Enable marginless templates and layouts, and it did not make a difference in the left/upward creep.

**Comment by mgobat** [comment]
Thanks for checking, @YvonneKester .

**Comment by mgobat** [comment]
@YvonneKester, what is your source for the measurements for the layout? Is it just from extensive testing, or do the measurements come with the label stock? While I don't see the measurements on the Demco website, I do see the Word templates. From that, it looks like 0.13 might be better for the horizontal gap and 0.12 for the vertical gap.  Does increasing your horizontal gap to 0.13 help with the shifting? If not, maybe try a little bit larger than that?

**Comment by YvonneKester** [comment]
Hi @mgobat ,

I have tried using precise measurements based on the specs printed on the back of each label sheet, and I have tried using just the measurements that come with the layout. I had also tried .13, but now I've tried .17 for the horizontal and .15 for the vertical, and we're finding much better results. Hopefully tomorrow when she gets in, the new template I'm adding with Default (Alma) call numbers will work. Thanks!

**Comment by mgobat** [comment]
@YvonneKester, glad there's some improvement with larger gaps. I look forward to hearing about the results from the users!

**Comment by YvonneKester** [comment]
Hi @mgobat ,

Well, I made one adjustment this morning, and they are all set, with the Default (Alma) call number template, too!

The final measurements for our layout:

Top margin: 0.69
Left margin: 0.3125
Label width: 0.875
Label height: 1.5
HORIZONTAL GAP: 0.17
VERTICAL GAP: 0.19
Left padding: 0.1

Thank you! Have a great day!

**Comment by mgobat** [comment]
That's great news, @YvonneKester. Thanks for sharing your settings.
